/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"

#import "EDAMLimits.h"

enum EDAMPrivilegeLevel {
  PrivilegeLevel_NORMAL = 1,
  PrivilegeLevel_PREMIUM = 3,
  PrivilegeLevel_MANAGER = 7,
  PrivilegeLevel_SUPPORT = 8,
  PrivilegeLevel_ADMIN = 9
};

enum EDAMQueryFormat {
  QueryFormat_USER = 1,
  QueryFormat_SEXP = 2
};

enum EDAMNoteSortOrder {
  NoteSortOrder_CREATED = 1,
  NoteSortOrder_UPDATED = 2,
  NoteSortOrder_RELEVANCE = 3,
  NoteSortOrder_UPDATE_SEQUENCE_NUMBER = 4,
  NoteSortOrder_TITLE = 5
};

enum EDAMPremiumOrderStatus {
  PremiumOrderStatus_NONE = 0,
  PremiumOrderStatus_PENDING = 1,
  PremiumOrderStatus_ACTIVE = 2,
  PremiumOrderStatus_FAILED = 3,
  PremiumOrderStatus_CANCELLATION_PENDING = 4,
  PremiumOrderStatus_CANCELED = 5
};

enum EDAMSharedNotebookPrivilegeLevel {
  SharedNotebookPrivilegeLevel_READ_NOTEBOOK = 0,
  SharedNotebookPrivilegeLevel_MODIFY_NOTEBOOK_PLUS_ACTIVITY = 1,
  SharedNotebookPrivilegeLevel_READ_NOTEBOOK_PLUS_ACTIVITY = 2,
  SharedNotebookPrivilegeLevel_GROUP = 3,
  SharedNotebookPrivilegeLevel_FULL_ACCESS = 4,
  SharedNotebookPrivilegeLevel_BUSINESS_FULL_ACCESS = 5
};

enum EDAMSponsoredGroupRole {
  SponsoredGroupRole_GROUP_MEMBER = 1,
  SponsoredGroupRole_GROUP_ADMIN = 2,
  SponsoredGroupRole_GROUP_OWNER = 3
};

enum EDAMBusinessUserRole {
  BusinessUserRole_ADMIN = 1,
  BusinessUserRole_NORMAL = 2
};

enum EDAMSharedNotebookInstanceRestrictions {
  SharedNotebookInstanceRestrictions_ONLY_JOINED_OR_PREVIEW = 1,
  SharedNotebookInstanceRestrictions_NO_SHARED_NOTEBOOKS = 2
};

typedef int32_t EDAMUserID;

typedef NSString * EDAMGuid;

typedef int64_t EDAMTimestamp;

@interface EDAMData : NSObject <NSCoding> {
  NSData * __bodyHash;
  int32_t __size;
  NSData * __body;

  BOOL __bodyHash_isset;
  BOOL __size_isset;
  BOOL __body_isset;
}

- (id) initWithBodyHash: (NSData *) bodyHash size: (int32_t) size body: (NSData *) body;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=bodyHash, setter=setBodyHash:) NSData * bodyHash;
@property (nonatomic, getter=size, setter=setSize:) int32_t size;
@property (nonatomic, retain, getter=body, setter=setBody:) NSData * body;
#else

- (NSData *) bodyHash;
- (void) setBodyHash: (NSData *) bodyHash;

- (int32_t) size;
- (void) setSize: (int32_t) size;

- (NSData *) body;
- (void) setBody: (NSData *) body;

#endif

- (BOOL) bodyHashIsSet;
- (BOOL) sizeIsSet;
- (BOOL) bodyIsSet;
@end

@interface EDAMUserAttributes : NSObject <NSCoding> {
  NSString * __defaultLocationName;
  double __defaultLatitude;
  double __defaultLongitude;
  BOOL __preactivation;
  NSArray * __viewedPromotions;
  NSString * __incomingEmailAddress;
  NSArray * __recentMailedAddresses;
  NSString * __comments;
  EDAMTimestamp __dateAgreedToTermsOfService;
  int32_t __maxReferrals;
  int32_t __referralCount;
  NSString * __refererCode;
  EDAMTimestamp __sentEmailDate;
  int32_t __sentEmailCount;
  int32_t __dailyEmailLimit;
  EDAMTimestamp __emailOptOutDate;
  EDAMTimestamp __partnerEmailOptInDate;
  NSString * __preferredLanguage;
  NSString * __preferredCountry;
  BOOL __clipFullPage;
  NSString * __twitterUserName;
  NSString * __twitterId;
  NSString * __groupName;
  NSString * __recognitionLanguage;
  int64_t __customerProfileId;
  NSString * __referralProof;
  BOOL __educationalDiscount;
  NSString * __businessAddress;
  BOOL __hideSponsorBilling;
  BOOL __taxExempt;

  BOOL __defaultLocationName_isset;
  BOOL __defaultLatitude_isset;
  BOOL __defaultLongitude_isset;
  BOOL __preactivation_isset;
  BOOL __viewedPromotions_isset;
  BOOL __incomingEmailAddress_isset;
  BOOL __recentMailedAddresses_isset;
  BOOL __comments_isset;
  BOOL __dateAgreedToTermsOfService_isset;
  BOOL __maxReferrals_isset;
  BOOL __referralCount_isset;
  BOOL __refererCode_isset;
  BOOL __sentEmailDate_isset;
  BOOL __sentEmailCount_isset;
  BOOL __dailyEmailLimit_isset;
  BOOL __emailOptOutDate_isset;
  BOOL __partnerEmailOptInDate_isset;
  BOOL __preferredLanguage_isset;
  BOOL __preferredCountry_isset;
  BOOL __clipFullPage_isset;
  BOOL __twitterUserName_isset;
  BOOL __twitterId_isset;
  BOOL __groupName_isset;
  BOOL __recognitionLanguage_isset;
  BOOL __customerProfileId_isset;
  BOOL __referralProof_isset;
  BOOL __educationalDiscount_isset;
  BOOL __businessAddress_isset;
  BOOL __hideSponsorBilling_isset;
  BOOL __taxExempt_isset;
}

- (id) initWithDefaultLocationName: (NSString *) defaultLocationName defaultLatitude: (double) defaultLatitude defaultLongitude: (double) defaultLongitude preactivation: (BOOL) preactivation viewedPromotions: (NSArray *) viewedPromotions incomingEmailAddress: (NSString *) incomingEmailAddress recentMailedAddresses: (NSArray *) recentMailedAddresses comments: (NSString *) comments dateAgreedToTermsOfService: (EDAMTimestamp) dateAgreedToTermsOfService maxReferrals: (int32_t) maxReferrals referralCount: (int32_t) referralCount refererCode: (NSString *) refererCode sentEmailDate: (EDAMTimestamp) sentEmailDate sentEmailCount: (int32_t) sentEmailCount dailyEmailLimit: (int32_t) dailyEmailLimit emailOptOutDate: (EDAMTimestamp) emailOptOutDate partnerEmailOptInDate: (EDAMTimestamp) partnerEmailOptInDate preferredLanguage: (NSString *) preferredLanguage preferredCountry: (NSString *) preferredCountry clipFullPage: (BOOL) clipFullPage twitterUserName: (NSString *) twitterUserName twitterId: (NSString *) twitterId groupName: (NSString *) groupName recognitionLanguage: (NSString *) recognitionLanguage customerProfileId: (int64_t) customerProfileId referralProof: (NSString *) referralProof educationalDiscount: (BOOL) educationalDiscount businessAddress: (NSString *) businessAddress hideSponsorBilling: (BOOL) hideSponsorBilling taxExempt: (BOOL) taxExempt;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=defaultLocationName, setter=setDefaultLocationName:) NSString * defaultLocationName;
@property (nonatomic, getter=defaultLatitude, setter=setDefaultLatitude:) double defaultLatitude;
@property (nonatomic, getter=defaultLongitude, setter=setDefaultLongitude:) double defaultLongitude;
@property (nonatomic, getter=preactivation, setter=setPreactivation:) BOOL preactivation;
@property (nonatomic, retain, getter=viewedPromotions, setter=setViewedPromotions:) NSArray * viewedPromotions;
@property (nonatomic, retain, getter=incomingEmailAddress, setter=setIncomingEmailAddress:) NSString * incomingEmailAddress;
@property (nonatomic, retain, getter=recentMailedAddresses, setter=setRecentMailedAddresses:) NSArray * recentMailedAddresses;
@property (nonatomic, retain, getter=comments, setter=setComments:) NSString * comments;
@property (nonatomic, getter=dateAgreedToTermsOfService, setter=setDateAgreedToTermsOfService:) EDAMTimestamp dateAgreedToTermsOfService;
@property (nonatomic, getter=maxReferrals, setter=setMaxReferrals:) int32_t maxReferrals;
@property (nonatomic, getter=referralCount, setter=setReferralCount:) int32_t referralCount;
@property (nonatomic, retain, getter=refererCode, setter=setRefererCode:) NSString * refererCode;
@property (nonatomic, getter=sentEmailDate, setter=setSentEmailDate:) EDAMTimestamp sentEmailDate;
@property (nonatomic, getter=sentEmailCount, setter=setSentEmailCount:) int32_t sentEmailCount;
@property (nonatomic, getter=dailyEmailLimit, setter=setDailyEmailLimit:) int32_t dailyEmailLimit;
@property (nonatomic, getter=emailOptOutDate, setter=setEmailOptOutDate:) EDAMTimestamp emailOptOutDate;
@property (nonatomic, getter=partnerEmailOptInDate, setter=setPartnerEmailOptInDate:) EDAMTimestamp partnerEmailOptInDate;
@property (nonatomic, retain, getter=preferredLanguage, setter=setPreferredLanguage:) NSString * preferredLanguage;
@property (nonatomic, retain, getter=preferredCountry, setter=setPreferredCountry:) NSString * preferredCountry;
@property (nonatomic, getter=clipFullPage, setter=setClipFullPage:) BOOL clipFullPage;
@property (nonatomic, retain, getter=twitterUserName, setter=setTwitterUserName:) NSString * twitterUserName;
@property (nonatomic, retain, getter=twitterId, setter=setTwitterId:) NSString * twitterId;
@property (nonatomic, retain, getter=groupName, setter=setGroupName:) NSString * groupName;
@property (nonatomic, retain, getter=recognitionLanguage, setter=setRecognitionLanguage:) NSString * recognitionLanguage;
@property (nonatomic, getter=customerProfileId, setter=setCustomerProfileId:) int64_t customerProfileId;
@property (nonatomic, retain, getter=referralProof, setter=setReferralProof:) NSString * referralProof;
@property (nonatomic, getter=educationalDiscount, setter=setEducationalDiscount:) BOOL educationalDiscount;
@property (nonatomic, retain, getter=businessAddress, setter=setBusinessAddress:) NSString * businessAddress;
@property (nonatomic, getter=hideSponsorBilling, setter=setHideSponsorBilling:) BOOL hideSponsorBilling;
@property (nonatomic, getter=taxExempt, setter=setTaxExempt:) BOOL taxExempt;
#else

- (NSString *) defaultLocationName;
- (void) setDefaultLocationName: (NSString *) defaultLocationName;

- (double) defaultLatitude;
- (void) setDefaultLatitude: (double) defaultLatitude;

- (double) defaultLongitude;
- (void) setDefaultLongitude: (double) defaultLongitude;

- (BOOL) preactivation;
- (void) setPreactivation: (BOOL) preactivation;

- (NSArray *) viewedPromotions;
- (void) setViewedPromotions: (NSArray *) viewedPromotions;

- (NSString *) incomingEmailAddress;
- (void) setIncomingEmailAddress: (NSString *) incomingEmailAddress;

- (NSArray *) recentMailedAddresses;
- (void) setRecentMailedAddresses: (NSArray *) recentMailedAddresses;

- (NSString *) comments;
- (void) setComments: (NSString *) comments;

- (EDAMTimestamp) dateAgreedToTermsOfService;
- (void) setDateAgreedToTermsOfService: (EDAMTimestamp) dateAgreedToTermsOfService;

- (int32_t) maxReferrals;
- (void) setMaxReferrals: (int32_t) maxReferrals;

- (int32_t) referralCount;
- (void) setReferralCount: (int32_t) referralCount;

- (NSString *) refererCode;
- (void) setRefererCode: (NSString *) refererCode;

- (EDAMTimestamp) sentEmailDate;
- (void) setSentEmailDate: (EDAMTimestamp) sentEmailDate;

- (int32_t) sentEmailCount;
- (void) setSentEmailCount: (int32_t) sentEmailCount;

- (int32_t) dailyEmailLimit;
- (void) setDailyEmailLimit: (int32_t) dailyEmailLimit;

- (EDAMTimestamp) emailOptOutDate;
- (void) setEmailOptOutDate: (EDAMTimestamp) emailOptOutDate;

- (EDAMTimestamp) partnerEmailOptInDate;
- (void) setPartnerEmailOptInDate: (EDAMTimestamp) partnerEmailOptInDate;

- (NSString *) preferredLanguage;
- (void) setPreferredLanguage: (NSString *) preferredLanguage;

- (NSString *) preferredCountry;
- (void) setPreferredCountry: (NSString *) preferredCountry;

- (BOOL) clipFullPage;
- (void) setClipFullPage: (BOOL) clipFullPage;

- (NSString *) twitterUserName;
- (void) setTwitterUserName: (NSString *) twitterUserName;

- (NSString *) twitterId;
- (void) setTwitterId: (NSString *) twitterId;

- (NSString *) groupName;
- (void) setGroupName: (NSString *) groupName;

- (NSString *) recognitionLanguage;
- (void) setRecognitionLanguage: (NSString *) recognitionLanguage;

- (int64_t) customerProfileId;
- (void) setCustomerProfileId: (int64_t) customerProfileId;

- (NSString *) referralProof;
- (void) setReferralProof: (NSString *) referralProof;

- (BOOL) educationalDiscount;
- (void) setEducationalDiscount: (BOOL) educationalDiscount;

- (NSString *) businessAddress;
- (void) setBusinessAddress: (NSString *) businessAddress;

- (BOOL) hideSponsorBilling;
- (void) setHideSponsorBilling: (BOOL) hideSponsorBilling;

- (BOOL) taxExempt;
- (void) setTaxExempt: (BOOL) taxExempt;

#endif

- (BOOL) defaultLocationNameIsSet;
- (BOOL) defaultLatitudeIsSet;
- (BOOL) defaultLongitudeIsSet;
- (BOOL) preactivationIsSet;
- (BOOL) viewedPromotionsIsSet;
- (BOOL) incomingEmailAddressIsSet;
- (BOOL) recentMailedAddressesIsSet;
- (BOOL) commentsIsSet;
- (BOOL) dateAgreedToTermsOfServiceIsSet;
- (BOOL) maxReferralsIsSet;
- (BOOL) referralCountIsSet;
- (BOOL) refererCodeIsSet;
- (BOOL) sentEmailDateIsSet;
- (BOOL) sentEmailCountIsSet;
- (BOOL) dailyEmailLimitIsSet;
- (BOOL) emailOptOutDateIsSet;
- (BOOL) partnerEmailOptInDateIsSet;
- (BOOL) preferredLanguageIsSet;
- (BOOL) preferredCountryIsSet;
- (BOOL) clipFullPageIsSet;
- (BOOL) twitterUserNameIsSet;
- (BOOL) twitterIdIsSet;
- (BOOL) groupNameIsSet;
- (BOOL) recognitionLanguageIsSet;
- (BOOL) customerProfileIdIsSet;
- (BOOL) referralProofIsSet;
- (BOOL) educationalDiscountIsSet;
- (BOOL) businessAddressIsSet;
- (BOOL) hideSponsorBillingIsSet;
- (BOOL) taxExemptIsSet;
@end

@interface EDAMAccounting : NSObject <NSCoding> {
  int64_t __uploadLimit;
  EDAMTimestamp __uploadLimitEnd;
  int64_t __uploadLimitNextMonth;
  int __premiumServiceStatus;
  NSString * __premiumOrderNumber;
  NSString * __premiumCommerceService;
  EDAMTimestamp __premiumServiceStart;
  NSString * __premiumServiceSKU;
  EDAMTimestamp __lastSuccessfulCharge;
  EDAMTimestamp __lastFailedCharge;
  NSString * __lastFailedChargeReason;
  EDAMTimestamp __nextPaymentDue;
  EDAMTimestamp __premiumLockUntil;
  EDAMTimestamp __updated;
  NSString * __premiumSubscriptionNumber;
  EDAMTimestamp __lastRequestedCharge;
  NSString * __currency;
  int32_t __unitPrice;
  int32_t __businessId;
  NSString * __businessName;
  int __businessRole;

  BOOL __uploadLimit_isset;
  BOOL __uploadLimitEnd_isset;
  BOOL __uploadLimitNextMonth_isset;
  BOOL __premiumServiceStatus_isset;
  BOOL __premiumOrderNumber_isset;
  BOOL __premiumCommerceService_isset;
  BOOL __premiumServiceStart_isset;
  BOOL __premiumServiceSKU_isset;
  BOOL __lastSuccessfulCharge_isset;
  BOOL __lastFailedCharge_isset;
  BOOL __lastFailedChargeReason_isset;
  BOOL __nextPaymentDue_isset;
  BOOL __premiumLockUntil_isset;
  BOOL __updated_isset;
  BOOL __premiumSubscriptionNumber_isset;
  BOOL __lastRequestedCharge_isset;
  BOOL __currency_isset;
  BOOL __unitPrice_isset;
  BOOL __businessId_isset;
  BOOL __businessName_isset;
  BOOL __businessRole_isset;
}

- (id) initWithUploadLimit: (int64_t) uploadLimit uploadLimitEnd: (EDAMTimestamp) uploadLimitEnd uploadLimitNextMonth: (int64_t) uploadLimitNextMonth premiumServiceStatus: (int) premiumServiceStatus premiumOrderNumber: (NSString *) premiumOrderNumber premiumCommerceService: (NSString *) premiumCommerceService premiumServiceStart: (EDAMTimestamp) premiumServiceStart premiumServiceSKU: (NSString *) premiumServiceSKU lastSuccessfulCharge: (EDAMTimestamp) lastSuccessfulCharge lastFailedCharge: (EDAMTimestamp) lastFailedCharge lastFailedChargeReason: (NSString *) lastFailedChargeReason nextPaymentDue: (EDAMTimestamp) nextPaymentDue premiumLockUntil: (EDAMTimestamp) premiumLockUntil updated: (EDAMTimestamp) updated premiumSubscriptionNumber: (NSString *) premiumSubscriptionNumber lastRequestedCharge: (EDAMTimestamp) lastRequestedCharge currency: (NSString *) currency unitPrice: (int32_t) unitPrice businessId: (int32_t) businessId businessName: (NSString *) businessName businessRole: (int) businessRole;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=uploadLimit, setter=setUploadLimit:) int64_t uploadLimit;
@property (nonatomic, getter=uploadLimitEnd, setter=setUploadLimitEnd:) EDAMTimestamp uploadLimitEnd;
@property (nonatomic, getter=uploadLimitNextMonth, setter=setUploadLimitNextMonth:) int64_t uploadLimitNextMonth;
@property (nonatomic, getter=premiumServiceStatus, setter=setPremiumServiceStatus:) int premiumServiceStatus;
@property (nonatomic, retain, getter=premiumOrderNumber, setter=setPremiumOrderNumber:) NSString * premiumOrderNumber;
@property (nonatomic, retain, getter=premiumCommerceService, setter=setPremiumCommerceService:) NSString * premiumCommerceService;
@property (nonatomic, getter=premiumServiceStart, setter=setPremiumServiceStart:) EDAMTimestamp premiumServiceStart;
@property (nonatomic, retain, getter=premiumServiceSKU, setter=setPremiumServiceSKU:) NSString * premiumServiceSKU;
@property (nonatomic, getter=lastSuccessfulCharge, setter=setLastSuccessfulCharge:) EDAMTimestamp lastSuccessfulCharge;
@property (nonatomic, getter=lastFailedCharge, setter=setLastFailedCharge:) EDAMTimestamp lastFailedCharge;
@property (nonatomic, retain, getter=lastFailedChargeReason, setter=setLastFailedChargeReason:) NSString * lastFailedChargeReason;
@property (nonatomic, getter=nextPaymentDue, setter=setNextPaymentDue:) EDAMTimestamp nextPaymentDue;
@property (nonatomic, getter=premiumLockUntil, setter=setPremiumLockUntil:) EDAMTimestamp premiumLockUntil;
@property (nonatomic, getter=updated, setter=setUpdated:) EDAMTimestamp updated;
@property (nonatomic, retain, getter=premiumSubscriptionNumber, setter=setPremiumSubscriptionNumber:) NSString * premiumSubscriptionNumber;
@property (nonatomic, getter=lastRequestedCharge, setter=setLastRequestedCharge:) EDAMTimestamp lastRequestedCharge;
@property (nonatomic, retain, getter=currency, setter=setCurrency:) NSString * currency;
@property (nonatomic, getter=unitPrice, setter=setUnitPrice:) int32_t unitPrice;
@property (nonatomic, getter=businessId, setter=setBusinessId:) int32_t businessId;
@property (nonatomic, retain, getter=businessName, setter=setBusinessName:) NSString * businessName;
@property (nonatomic, getter=businessRole, setter=setBusinessRole:) int businessRole;
#else

- (int64_t) uploadLimit;
- (void) setUploadLimit: (int64_t) uploadLimit;

- (EDAMTimestamp) uploadLimitEnd;
- (void) setUploadLimitEnd: (EDAMTimestamp) uploadLimitEnd;

- (int64_t) uploadLimitNextMonth;
- (void) setUploadLimitNextMonth: (int64_t) uploadLimitNextMonth;

- (int) premiumServiceStatus;
- (void) setPremiumServiceStatus: (int) premiumServiceStatus;

- (NSString *) premiumOrderNumber;
- (void) setPremiumOrderNumber: (NSString *) premiumOrderNumber;

- (NSString *) premiumCommerceService;
- (void) setPremiumCommerceService: (NSString *) premiumCommerceService;

- (EDAMTimestamp) premiumServiceStart;
- (void) setPremiumServiceStart: (EDAMTimestamp) premiumServiceStart;

- (NSString *) premiumServiceSKU;
- (void) setPremiumServiceSKU: (NSString *) premiumServiceSKU;

- (EDAMTimestamp) lastSuccessfulCharge;
- (void) setLastSuccessfulCharge: (EDAMTimestamp) lastSuccessfulCharge;

- (EDAMTimestamp) lastFailedCharge;
- (void) setLastFailedCharge: (EDAMTimestamp) lastFailedCharge;

- (NSString *) lastFailedChargeReason;
- (void) setLastFailedChargeReason: (NSString *) lastFailedChargeReason;

- (EDAMTimestamp) nextPaymentDue;
- (void) setNextPaymentDue: (EDAMTimestamp) nextPaymentDue;

- (EDAMTimestamp) premiumLockUntil;
- (void) setPremiumLockUntil: (EDAMTimestamp) premiumLockUntil;

- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;

- (NSString *) premiumSubscriptionNumber;
- (void) setPremiumSubscriptionNumber: (NSString *) premiumSubscriptionNumber;

- (EDAMTimestamp) lastRequestedCharge;
- (void) setLastRequestedCharge: (EDAMTimestamp) lastRequestedCharge;

- (NSString *) currency;
- (void) setCurrency: (NSString *) currency;

- (int32_t) unitPrice;
- (void) setUnitPrice: (int32_t) unitPrice;

- (int32_t) businessId;
- (void) setBusinessId: (int32_t) businessId;

- (NSString *) businessName;
- (void) setBusinessName: (NSString *) businessName;

- (int) businessRole;
- (void) setBusinessRole: (int) businessRole;

#endif

- (BOOL) uploadLimitIsSet;
- (BOOL) uploadLimitEndIsSet;
- (BOOL) uploadLimitNextMonthIsSet;
- (BOOL) premiumServiceStatusIsSet;
- (BOOL) premiumOrderNumberIsSet;
- (BOOL) premiumCommerceServiceIsSet;
- (BOOL) premiumServiceStartIsSet;
- (BOOL) premiumServiceSKUIsSet;
- (BOOL) lastSuccessfulChargeIsSet;
- (BOOL) lastFailedChargeIsSet;
- (BOOL) lastFailedChargeReasonIsSet;
- (BOOL) nextPaymentDueIsSet;
- (BOOL) premiumLockUntilIsSet;
- (BOOL) updatedIsSet;
- (BOOL) premiumSubscriptionNumberIsSet;
- (BOOL) lastRequestedChargeIsSet;
- (BOOL) currencyIsSet;
- (BOOL) unitPriceIsSet;
- (BOOL) businessIdIsSet;
- (BOOL) businessNameIsSet;
- (BOOL) businessRoleIsSet;
@end

@interface EDAMPremiumInfo : NSObject <NSCoding> {
  EDAMTimestamp __currentTime;
  BOOL __premium;
  BOOL __premiumRecurring;
  EDAMTimestamp __premiumExpirationDate;
  BOOL __premiumExtendable;
  BOOL __premiumPending;
  BOOL __premiumCancellationPending;
  BOOL __canPurchaseUploadAllowance;
  NSString * __sponsoredGroupName;
  int __sponsoredGroupRole;

  BOOL __currentTime_isset;
  BOOL __premium_isset;
  BOOL __premiumRecurring_isset;
  BOOL __premiumExpirationDate_isset;
  BOOL __premiumExtendable_isset;
  BOOL __premiumPending_isset;
  BOOL __premiumCancellationPending_isset;
  BOOL __canPurchaseUploadAllowance_isset;
  BOOL __sponsoredGroupName_isset;
  BOOL __sponsoredGroupRole_isset;
}

- (id) initWithCurrentTime: (EDAMTimestamp) currentTime premium: (BOOL) premium premiumRecurring: (BOOL) premiumRecurring premiumExpirationDate: (EDAMTimestamp) premiumExpirationDate premiumExtendable: (BOOL) premiumExtendable premiumPending: (BOOL) premiumPending premiumCancellationPending: (BOOL) premiumCancellationPending canPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance sponsoredGroupName: (NSString *) sponsoredGroupName sponsoredGroupRole: (int) sponsoredGroupRole;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentTime, setter=setCurrentTime:) EDAMTimestamp currentTime;
@property (nonatomic, getter=premium, setter=setPremium:) BOOL premium;
@property (nonatomic, getter=premiumRecurring, setter=setPremiumRecurring:) BOOL premiumRecurring;
@property (nonatomic, getter=premiumExpirationDate, setter=setPremiumExpirationDate:) EDAMTimestamp premiumExpirationDate;
@property (nonatomic, getter=premiumExtendable, setter=setPremiumExtendable:) BOOL premiumExtendable;
@property (nonatomic, getter=premiumPending, setter=setPremiumPending:) BOOL premiumPending;
@property (nonatomic, getter=premiumCancellationPending, setter=setPremiumCancellationPending:) BOOL premiumCancellationPending;
@property (nonatomic, getter=canPurchaseUploadAllowance, setter=setCanPurchaseUploadAllowance:) BOOL canPurchaseUploadAllowance;
@property (nonatomic, retain, getter=sponsoredGroupName, setter=setSponsoredGroupName:) NSString * sponsoredGroupName;
@property (nonatomic, getter=sponsoredGroupRole, setter=setSponsoredGroupRole:) int sponsoredGroupRole;
#else

- (EDAMTimestamp) currentTime;
- (void) setCurrentTime: (EDAMTimestamp) currentTime;

- (BOOL) premium;
- (void) setPremium: (BOOL) premium;

- (BOOL) premiumRecurring;
- (void) setPremiumRecurring: (BOOL) premiumRecurring;

- (EDAMTimestamp) premiumExpirationDate;
- (void) setPremiumExpirationDate: (EDAMTimestamp) premiumExpirationDate;

- (BOOL) premiumExtendable;
- (void) setPremiumExtendable: (BOOL) premiumExtendable;

- (BOOL) premiumPending;
- (void) setPremiumPending: (BOOL) premiumPending;

- (BOOL) premiumCancellationPending;
- (void) setPremiumCancellationPending: (BOOL) premiumCancellationPending;

- (BOOL) canPurchaseUploadAllowance;
- (void) setCanPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance;

- (NSString *) sponsoredGroupName;
- (void) setSponsoredGroupName: (NSString *) sponsoredGroupName;

- (int) sponsoredGroupRole;
- (void) setSponsoredGroupRole: (int) sponsoredGroupRole;

#endif

- (BOOL) currentTimeIsSet;
- (BOOL) premiumIsSet;
- (BOOL) premiumRecurringIsSet;
- (BOOL) premiumExpirationDateIsSet;
- (BOOL) premiumExtendableIsSet;
- (BOOL) premiumPendingIsSet;
- (BOOL) premiumCancellationPendingIsSet;
- (BOOL) canPurchaseUploadAllowanceIsSet;
- (BOOL) sponsoredGroupNameIsSet;
- (BOOL) sponsoredGroupRoleIsSet;
@end

@interface EDAMUser : NSObject <NSCoding> {
  EDAMUserID __id;
  NSString * __username;
  NSString * __email;
  NSString * __name;
  NSString * __timezone;
  int __privilege;
  EDAMTimestamp __created;
  EDAMTimestamp __updated;
  EDAMTimestamp __deleted;
  BOOL __active;
  NSString * __shardId;
  EDAMUserAttributes * __attributes;
  EDAMAccounting * __accounting;
  EDAMPremiumInfo * __premiumInfo;

  BOOL __id_isset;
  BOOL __username_isset;
  BOOL __email_isset;
  BOOL __name_isset;
  BOOL __timezone_isset;
  BOOL __privilege_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
  BOOL __deleted_isset;
  BOOL __active_isset;
  BOOL __shardId_isset;
  BOOL __attributes_isset;
  BOOL __accounting_isset;
  BOOL __premiumInfo_isset;
}

- (id) initWithId: (EDAMUserID) id username: (NSString *) username email: (NSString *) email name: (NSString *) name timezone: (NSString *) timezone privilege: (int) privilege created: (EDAMTimestamp) created updated: (EDAMTimestamp) updated deleted: (EDAMTimestamp) deleted active: (BOOL) active shardId: (NSString *) shardId attributes: (EDAMUserAttributes *) attributes accounting: (EDAMAccounting *) accounting premiumInfo: (EDAMPremiumInfo *) premiumInfo;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) EDAMUserID id;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=timezone, setter=setTimezone:) NSString * timezone;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, getter=created, setter=setCreated:) EDAMTimestamp created;
@property (nonatomic, getter=updated, setter=setUpdated:) EDAMTimestamp updated;
@property (nonatomic, getter=deleted, setter=setDeleted:) EDAMTimestamp deleted;
@property (nonatomic, getter=active, setter=setActive:) BOOL active;
@property (nonatomic, retain, getter=shardId, setter=setShardId:) NSString * shardId;
@property (nonatomic, retain, getter=attributes, setter=setAttributes:) EDAMUserAttributes * attributes;
@property (nonatomic, retain, getter=accounting, setter=setAccounting:) EDAMAccounting * accounting;
@property (nonatomic, retain, getter=premiumInfo, setter=setPremiumInfo:) EDAMPremiumInfo * premiumInfo;
#else

- (EDAMUserID) id;
- (void) setId: (EDAMUserID) id;

- (NSString *) username;
- (void) setUsername: (NSString *) username;

- (NSString *) email;
- (void) setEmail: (NSString *) email;

- (NSString *) name;
- (void) setName: (NSString *) name;

- (NSString *) timezone;
- (void) setTimezone: (NSString *) timezone;

- (int) privilege;
- (void) setPrivilege: (int) privilege;

- (EDAMTimestamp) created;
- (void) setCreated: (EDAMTimestamp) created;

- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;

- (EDAMTimestamp) deleted;
- (void) setDeleted: (EDAMTimestamp) deleted;

- (BOOL) active;
- (void) setActive: (BOOL) active;

- (NSString *) shardId;
- (void) setShardId: (NSString *) shardId;

- (EDAMUserAttributes *) attributes;
- (void) setAttributes: (EDAMUserAttributes *) attributes;

- (EDAMAccounting *) accounting;
- (void) setAccounting: (EDAMAccounting *) accounting;

- (EDAMPremiumInfo *) premiumInfo;
- (void) setPremiumInfo: (EDAMPremiumInfo *) premiumInfo;

#endif

- (BOOL) idIsSet;
- (BOOL) usernameIsSet;
- (BOOL) emailIsSet;
- (BOOL) nameIsSet;
- (BOOL) timezoneIsSet;
- (BOOL) privilegeIsSet;
- (BOOL) createdIsSet;
- (BOOL) updatedIsSet;
- (BOOL) deletedIsSet;
- (BOOL) activeIsSet;
- (BOOL) shardIdIsSet;
- (BOOL) attributesIsSet;
- (BOOL) accountingIsSet;
- (BOOL) premiumInfoIsSet;
@end

@interface EDAMTag : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __name;
  EDAMGuid __parentGuid;
  int32_t __updateSequenceNum;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __parentGuid_isset;
  BOOL __updateSequenceNum_isset;
}

- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name parentGuid: (EDAMGuid) parentGuid updateSequenceNum: (int32_t) updateSequenceNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=parentGuid, setter=setParentGuid:) EDAMGuid parentGuid;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
#else

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;

- (NSString *) name;
- (void) setName: (NSString *) name;

- (EDAMGuid) parentGuid;
- (void) setParentGuid: (EDAMGuid) parentGuid;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;

#endif

- (BOOL) guidIsSet;
- (BOOL) nameIsSet;
- (BOOL) parentGuidIsSet;
- (BOOL) updateSequenceNumIsSet;
@end

@interface EDAMLazyMap : NSObject <NSCoding> {
  NSSet * __keysOnly;
  NSDictionary * __fullMap;

  BOOL __keysOnly_isset;
  BOOL __fullMap_isset;
}

- (id) initWithKeysOnly: (NSSet *) keysOnly fullMap: (NSDictionary *) fullMap;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=keysOnly, setter=setKeysOnly:) NSSet * keysOnly;
@property (nonatomic, retain, getter=fullMap, setter=setFullMap:) NSDictionary * fullMap;
#else

- (NSSet *) keysOnly;
- (void) setKeysOnly: (NSSet *) keysOnly;

- (NSDictionary *) fullMap;
- (void) setFullMap: (NSDictionary *) fullMap;

#endif

- (BOOL) keysOnlyIsSet;
- (BOOL) fullMapIsSet;
@end

@interface EDAMResourceAttributes : NSObject <NSCoding> {
  NSString * __sourceURL;
  EDAMTimestamp __timestamp;
  double __latitude;
  double __longitude;
  double __altitude;
  NSString * __cameraMake;
  NSString * __cameraModel;
  BOOL __clientWillIndex;
  NSString * __recoType;
  NSString * __fileName;
  BOOL __attachment;
  EDAMLazyMap * __applicationData;

  BOOL __sourceURL_isset;
  BOOL __timestamp_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
  BOOL __altitude_isset;
  BOOL __cameraMake_isset;
  BOOL __cameraModel_isset;
  BOOL __clientWillIndex_isset;
  BOOL __recoType_isset;
  BOOL __fileName_isset;
  BOOL __attachment_isset;
  BOOL __applicationData_isset;
}

- (id) initWithSourceURL: (NSString *) sourceURL timestamp: (EDAMTimestamp) timestamp latitude: (double) latitude longitude: (double) longitude altitude: (double) altitude cameraMake: (NSString *) cameraMake cameraModel: (NSString *) cameraModel clientWillIndex: (BOOL) clientWillIndex recoType: (NSString *) recoType fileName: (NSString *) fileName attachment: (BOOL) attachment applicationData: (EDAMLazyMap *) applicationData;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=sourceURL, setter=setSourceURL:) NSString * sourceURL;
@property (nonatomic, getter=timestamp, setter=setTimestamp:) EDAMTimestamp timestamp;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
@property (nonatomic, getter=altitude, setter=setAltitude:) double altitude;
@property (nonatomic, retain, getter=cameraMake, setter=setCameraMake:) NSString * cameraMake;
@property (nonatomic, retain, getter=cameraModel, setter=setCameraModel:) NSString * cameraModel;
@property (nonatomic, getter=clientWillIndex, setter=setClientWillIndex:) BOOL clientWillIndex;
@property (nonatomic, retain, getter=recoType, setter=setRecoType:) NSString * recoType;
@property (nonatomic, retain, getter=fileName, setter=setFileName:) NSString * fileName;
@property (nonatomic, getter=attachment, setter=setAttachment:) BOOL attachment;
@property (nonatomic, retain, getter=applicationData, setter=setApplicationData:) EDAMLazyMap * applicationData;
#else

- (NSString *) sourceURL;
- (void) setSourceURL: (NSString *) sourceURL;

- (EDAMTimestamp) timestamp;
- (void) setTimestamp: (EDAMTimestamp) timestamp;

- (double) latitude;
- (void) setLatitude: (double) latitude;

- (double) longitude;
- (void) setLongitude: (double) longitude;

- (double) altitude;
- (void) setAltitude: (double) altitude;

- (NSString *) cameraMake;
- (void) setCameraMake: (NSString *) cameraMake;

- (NSString *) cameraModel;
- (void) setCameraModel: (NSString *) cameraModel;

- (BOOL) clientWillIndex;
- (void) setClientWillIndex: (BOOL) clientWillIndex;

- (NSString *) recoType;
- (void) setRecoType: (NSString *) recoType;

- (NSString *) fileName;
- (void) setFileName: (NSString *) fileName;

- (BOOL) attachment;
- (void) setAttachment: (BOOL) attachment;

- (EDAMLazyMap *) applicationData;
- (void) setApplicationData: (EDAMLazyMap *) applicationData;

#endif

- (BOOL) sourceURLIsSet;
- (BOOL) timestampIsSet;
- (BOOL) latitudeIsSet;
- (BOOL) longitudeIsSet;
- (BOOL) altitudeIsSet;
- (BOOL) cameraMakeIsSet;
- (BOOL) cameraModelIsSet;
- (BOOL) clientWillIndexIsSet;
- (BOOL) recoTypeIsSet;
- (BOOL) fileNameIsSet;
- (BOOL) attachmentIsSet;
- (BOOL) applicationDataIsSet;
@end

@interface EDAMResource : NSObject <NSCoding> {
  EDAMGuid __guid;
  EDAMGuid __noteGuid;
  EDAMData * __data;
  NSString * __mime;
  int16_t __width;
  int16_t __height;
  int16_t __duration;
  BOOL __active;
  EDAMData * __recognition;
  EDAMResourceAttributes * __attributes;
  int32_t __updateSequenceNum;
  EDAMData * __alternateData;

  BOOL __guid_isset;
  BOOL __noteGuid_isset;
  BOOL __data_isset;
  BOOL __mime_isset;
  BOOL __width_isset;
  BOOL __height_isset;
  BOOL __duration_isset;
  BOOL __active_isset;
  BOOL __recognition_isset;
  BOOL __attributes_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __alternateData_isset;
}

- (id) initWithGuid: (EDAMGuid) guid noteGuid: (EDAMGuid) noteGuid data: (EDAMData *) data mime: (NSString *) mime width: (int16_t) width height: (int16_t) height duration: (int16_t) duration active: (BOOL) active recognition: (EDAMData *) recognition attributes: (EDAMResourceAttributes *) attributes updateSequenceNum: (int32_t) updateSequenceNum alternateData: (EDAMData *) alternateData;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, retain, getter=noteGuid, setter=setNoteGuid:) EDAMGuid noteGuid;
@property (nonatomic, retain, getter=data, setter=setData:) EDAMData * data;
@property (nonatomic, retain, getter=mime, setter=setMime:) NSString * mime;
@property (nonatomic, getter=width, setter=setWidth:) int16_t width;
@property (nonatomic, getter=height, setter=setHeight:) int16_t height;
@property (nonatomic, getter=duration, setter=setDuration:) int16_t duration;
@property (nonatomic, getter=active, setter=setActive:) BOOL active;
@property (nonatomic, retain, getter=recognition, setter=setRecognition:) EDAMData * recognition;
@property (nonatomic, retain, getter=attributes, setter=setAttributes:) EDAMResourceAttributes * attributes;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
@property (nonatomic, retain, getter=alternateData, setter=setAlternateData:) EDAMData * alternateData;
#else

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;

- (EDAMGuid) noteGuid;
- (void) setNoteGuid: (EDAMGuid) noteGuid;

- (EDAMData *) data;
- (void) setData: (EDAMData *) data;

- (NSString *) mime;
- (void) setMime: (NSString *) mime;

- (int16_t) width;
- (void) setWidth: (int16_t) width;

- (int16_t) height;
- (void) setHeight: (int16_t) height;

- (int16_t) duration;
- (void) setDuration: (int16_t) duration;

- (BOOL) active;
- (void) setActive: (BOOL) active;

- (EDAMData *) recognition;
- (void) setRecognition: (EDAMData *) recognition;

- (EDAMResourceAttributes *) attributes;
- (void) setAttributes: (EDAMResourceAttributes *) attributes;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;

- (EDAMData *) alternateData;
- (void) setAlternateData: (EDAMData *) alternateData;

#endif

- (BOOL) guidIsSet;
- (BOOL) noteGuidIsSet;
- (BOOL) dataIsSet;
- (BOOL) mimeIsSet;
- (BOOL) widthIsSet;
- (BOOL) heightIsSet;
- (BOOL) durationIsSet;
- (BOOL) activeIsSet;
- (BOOL) recognitionIsSet;
- (BOOL) attributesIsSet;
- (BOOL) updateSequenceNumIsSet;
- (BOOL) alternateDataIsSet;
@end

@interface EDAMNoteAttributes : NSObject <NSCoding> {
  EDAMTimestamp __subjectDate;
  double __latitude;
  double __longitude;
  double __altitude;
  NSString * __author;
  NSString * __source;
  NSString * __sourceURL;
  NSString * __sourceApplication;
  EDAMTimestamp __shareDate;
  NSString * __placeName;
  NSString * __contentClass;
  EDAMLazyMap * __applicationData;
  NSString * __lastEditedBy;
  NSDictionary * __classifications;

  BOOL __subjectDate_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
  BOOL __altitude_isset;
  BOOL __author_isset;
  BOOL __source_isset;
  BOOL __sourceURL_isset;
  BOOL __sourceApplication_isset;
  BOOL __shareDate_isset;
  BOOL __placeName_isset;
  BOOL __contentClass_isset;
  BOOL __applicationData_isset;
  BOOL __lastEditedBy_isset;
  BOOL __classifications_isset;
}

- (id) initWithSubjectDate: (EDAMTimestamp) subjectDate latitude: (double) latitude longitude: (double) longitude altitude: (double) altitude author: (NSString *) author source: (NSString *) source sourceURL: (NSString *) sourceURL sourceApplication: (NSString *) sourceApplication shareDate: (EDAMTimestamp) shareDate placeName: (NSString *) placeName contentClass: (NSString *) contentClass applicationData: (EDAMLazyMap *) applicationData lastEditedBy: (NSString *) lastEditedBy classifications: (NSDictionary *) classifications;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=subjectDate, setter=setSubjectDate:) EDAMTimestamp subjectDate;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
@property (nonatomic, getter=altitude, setter=setAltitude:) double altitude;
@property (nonatomic, retain, getter=author, setter=setAuthor:) NSString * author;
@property (nonatomic, retain, getter=source, setter=setSource:) NSString * source;
@property (nonatomic, retain, getter=sourceURL, setter=setSourceURL:) NSString * sourceURL;
@property (nonatomic, retain, getter=sourceApplication, setter=setSourceApplication:) NSString * sourceApplication;
@property (nonatomic, getter=shareDate, setter=setShareDate:) EDAMTimestamp shareDate;
@property (nonatomic, retain, getter=placeName, setter=setPlaceName:) NSString * placeName;
@property (nonatomic, retain, getter=contentClass, setter=setContentClass:) NSString * contentClass;
@property (nonatomic, retain, getter=applicationData, setter=setApplicationData:) EDAMLazyMap * applicationData;
@property (nonatomic, retain, getter=lastEditedBy, setter=setLastEditedBy:) NSString * lastEditedBy;
@property (nonatomic, retain, getter=classifications, setter=setClassifications:) NSDictionary * classifications;
#else

- (EDAMTimestamp) subjectDate;
- (void) setSubjectDate: (EDAMTimestamp) subjectDate;

- (double) latitude;
- (void) setLatitude: (double) latitude;

- (double) longitude;
- (void) setLongitude: (double) longitude;

- (double) altitude;
- (void) setAltitude: (double) altitude;

- (NSString *) author;
- (void) setAuthor: (NSString *) author;

- (NSString *) source;
- (void) setSource: (NSString *) source;

- (NSString *) sourceURL;
- (void) setSourceURL: (NSString *) sourceURL;

- (NSString *) sourceApplication;
- (void) setSourceApplication: (NSString *) sourceApplication;

- (EDAMTimestamp) shareDate;
- (void) setShareDate: (EDAMTimestamp) shareDate;

- (NSString *) placeName;
- (void) setPlaceName: (NSString *) placeName;

- (NSString *) contentClass;
- (void) setContentClass: (NSString *) contentClass;

- (EDAMLazyMap *) applicationData;
- (void) setApplicationData: (EDAMLazyMap *) applicationData;

- (NSString *) lastEditedBy;
- (void) setLastEditedBy: (NSString *) lastEditedBy;

- (NSDictionary *) classifications;
- (void) setClassifications: (NSDictionary *) classifications;

#endif

- (BOOL) subjectDateIsSet;
- (BOOL) latitudeIsSet;
- (BOOL) longitudeIsSet;
- (BOOL) altitudeIsSet;
- (BOOL) authorIsSet;
- (BOOL) sourceIsSet;
- (BOOL) sourceURLIsSet;
- (BOOL) sourceApplicationIsSet;
- (BOOL) shareDateIsSet;
- (BOOL) placeNameIsSet;
- (BOOL) contentClassIsSet;
- (BOOL) applicationDataIsSet;
- (BOOL) lastEditedByIsSet;
- (BOOL) classificationsIsSet;
@end

@interface EDAMNote : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __title;
  NSString * __content;
  NSData * __contentHash;
  int32_t __contentLength;
  EDAMTimestamp __created;
  EDAMTimestamp __updated;
  EDAMTimestamp __deleted;
  BOOL __active;
  int32_t __updateSequenceNum;
  NSString * __notebookGuid;
  NSArray * __tagGuids;
  NSArray * __resources;
  EDAMNoteAttributes * __attributes;
  NSArray * __tagNames;

  BOOL __guid_isset;
  BOOL __title_isset;
  BOOL __content_isset;
  BOOL __contentHash_isset;
  BOOL __contentLength_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
  BOOL __deleted_isset;
  BOOL __active_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __notebookGuid_isset;
  BOOL __tagGuids_isset;
  BOOL __resources_isset;
  BOOL __attributes_isset;
  BOOL __tagNames_isset;
}

- (id) initWithGuid: (EDAMGuid) guid title: (NSString *) title content: (NSString *) content contentHash: (NSData *) contentHash contentLength: (int32_t) contentLength created: (EDAMTimestamp) created updated: (EDAMTimestamp) updated deleted: (EDAMTimestamp) deleted active: (BOOL) active updateSequenceNum: (int32_t) updateSequenceNum notebookGuid: (NSString *) notebookGuid tagGuids: (NSArray *) tagGuids resources: (NSArray *) resources attributes: (EDAMNoteAttributes *) attributes tagNames: (NSArray *) tagNames;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, retain, getter=content, setter=setContent:) NSString * content;
@property (nonatomic, retain, getter=contentHash, setter=setContentHash:) NSData * contentHash;
@property (nonatomic, getter=contentLength, setter=setContentLength:) int32_t contentLength;
@property (nonatomic, getter=created, setter=setCreated:) EDAMTimestamp created;
@property (nonatomic, getter=updated, setter=setUpdated:) EDAMTimestamp updated;
@property (nonatomic, getter=deleted, setter=setDeleted:) EDAMTimestamp deleted;
@property (nonatomic, getter=active, setter=setActive:) BOOL active;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
@property (nonatomic, retain, getter=notebookGuid, setter=setNotebookGuid:) NSString * notebookGuid;
@property (nonatomic, retain, getter=tagGuids, setter=setTagGuids:) NSArray * tagGuids;
@property (nonatomic, retain, getter=resources, setter=setResources:) NSArray * resources;
@property (nonatomic, retain, getter=attributes, setter=setAttributes:) EDAMNoteAttributes * attributes;
@property (nonatomic, retain, getter=tagNames, setter=setTagNames:) NSArray * tagNames;
#else

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;

- (NSString *) title;
- (void) setTitle: (NSString *) title;

- (NSString *) content;
- (void) setContent: (NSString *) content;

- (NSData *) contentHash;
- (void) setContentHash: (NSData *) contentHash;

- (int32_t) contentLength;
- (void) setContentLength: (int32_t) contentLength;

- (EDAMTimestamp) created;
- (void) setCreated: (EDAMTimestamp) created;

- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;

- (EDAMTimestamp) deleted;
- (void) setDeleted: (EDAMTimestamp) deleted;

- (BOOL) active;
- (void) setActive: (BOOL) active;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;

- (NSString *) notebookGuid;
- (void) setNotebookGuid: (NSString *) notebookGuid;

- (NSArray *) tagGuids;
- (void) setTagGuids: (NSArray *) tagGuids;

- (NSArray *) resources;
- (void) setResources: (NSArray *) resources;

- (EDAMNoteAttributes *) attributes;
- (void) setAttributes: (EDAMNoteAttributes *) attributes;

- (NSArray *) tagNames;
- (void) setTagNames: (NSArray *) tagNames;

#endif

- (BOOL) guidIsSet;
- (BOOL) titleIsSet;
- (BOOL) contentIsSet;
- (BOOL) contentHashIsSet;
- (BOOL) contentLengthIsSet;
- (BOOL) createdIsSet;
- (BOOL) updatedIsSet;
- (BOOL) deletedIsSet;
- (BOOL) activeIsSet;
- (BOOL) updateSequenceNumIsSet;
- (BOOL) notebookGuidIsSet;
- (BOOL) tagGuidsIsSet;
- (BOOL) resourcesIsSet;
- (BOOL) attributesIsSet;
- (BOOL) tagNamesIsSet;
@end

@interface EDAMPublishing : NSObject <NSCoding> {
  NSString * __uri;
  int __order;
  BOOL __ascending;
  NSString * __publicDescription;

  BOOL __uri_isset;
  BOOL __order_isset;
  BOOL __ascending_isset;
  BOOL __publicDescription_isset;
}

- (id) initWithUri: (NSString *) uri order: (int) order ascending: (BOOL) ascending publicDescription: (NSString *) publicDescription;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=uri, setter=setUri:) NSString * uri;
@property (nonatomic, getter=order, setter=setOrder:) int order;
@property (nonatomic, getter=ascending, setter=setAscending:) BOOL ascending;
@property (nonatomic, retain, getter=publicDescription, setter=setPublicDescription:) NSString * publicDescription;
#else

- (NSString *) uri;
- (void) setUri: (NSString *) uri;

- (int) order;
- (void) setOrder: (int) order;

- (BOOL) ascending;
- (void) setAscending: (BOOL) ascending;

- (NSString *) publicDescription;
- (void) setPublicDescription: (NSString *) publicDescription;

#endif

- (BOOL) uriIsSet;
- (BOOL) orderIsSet;
- (BOOL) ascendingIsSet;
- (BOOL) publicDescriptionIsSet;
@end

@interface EDAMBusinessNotebook : NSObject <NSCoding> {
  NSString * __notebookDescription;
  int __privilege;
  BOOL __recommended;

  BOOL __notebookDescription_isset;
  BOOL __privilege_isset;
  BOOL __recommended_isset;
}

- (id) initWithNotebookDescription: (NSString *) notebookDescription privilege: (int) privilege recommended: (BOOL) recommended;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=notebookDescription, setter=setNotebookDescription:) NSString * notebookDescription;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, getter=recommended, setter=setRecommended:) BOOL recommended;
#else

- (NSString *) notebookDescription;
- (void) setNotebookDescription: (NSString *) notebookDescription;

- (int) privilege;
- (void) setPrivilege: (int) privilege;

- (BOOL) recommended;
- (void) setRecommended: (BOOL) recommended;

#endif

- (BOOL) notebookDescriptionIsSet;
- (BOOL) privilegeIsSet;
- (BOOL) recommendedIsSet;
@end

@interface EDAMSavedSearch : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __name;
  NSString * __query;
  int __format;
  int32_t __updateSequenceNum;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __query_isset;
  BOOL __format_isset;
  BOOL __updateSequenceNum_isset;
}

- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name query: (NSString *) query format: (int) format updateSequenceNum: (int32_t) updateSequenceNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=query, setter=setQuery:) NSString * query;
@property (nonatomic, getter=format, setter=setFormat:) int format;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
#else

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;

- (NSString *) name;
- (void) setName: (NSString *) name;

- (NSString *) query;
- (void) setQuery: (NSString *) query;

- (int) format;
- (void) setFormat: (int) format;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;

#endif

- (BOOL) guidIsSet;
- (BOOL) nameIsSet;
- (BOOL) queryIsSet;
- (BOOL) formatIsSet;
- (BOOL) updateSequenceNumIsSet;
@end

@interface EDAMSharedNotebook : NSObject <NSCoding> {
  int64_t __id;
  int32_t __userId;
  NSString * __notebookGuid;
  NSString * __email;
  BOOL __notebookModifiable;
  BOOL __requireLogin;
  EDAMTimestamp __serviceCreated;
  EDAMTimestamp __serviceUpdated;
  NSString * __shareKey;
  NSString * __username;
  int __privilege;
  BOOL __allowPreview;

  BOOL __id_isset;
  BOOL __userId_isset;
  BOOL __notebookGuid_isset;
  BOOL __email_isset;
  BOOL __notebookModifiable_isset;
  BOOL __requireLogin_isset;
  BOOL __serviceCreated_isset;
  BOOL __serviceUpdated_isset;
  BOOL __shareKey_isset;
  BOOL __username_isset;
  BOOL __privilege_isset;
  BOOL __allowPreview_isset;
}

- (id) initWithId: (int64_t) id userId: (int32_t) userId notebookGuid: (NSString *) notebookGuid email: (NSString *) email notebookModifiable: (BOOL) notebookModifiable requireLogin: (BOOL) requireLogin serviceCreated: (EDAMTimestamp) serviceCreated serviceUpdated: (EDAMTimestamp) serviceUpdated shareKey: (NSString *) shareKey username: (NSString *) username privilege: (int) privilege allowPreview: (BOOL) allowPreview;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, getter=userId, setter=setUserId:) int32_t userId;
@property (nonatomic, retain, getter=notebookGuid, setter=setNotebookGuid:) NSString * notebookGuid;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, getter=notebookModifiable, setter=setNotebookModifiable:) BOOL notebookModifiable;
@property (nonatomic, getter=requireLogin, setter=setRequireLogin:) BOOL requireLogin;
@property (nonatomic, getter=serviceCreated, setter=setServiceCreated:) EDAMTimestamp serviceCreated;
@property (nonatomic, getter=serviceUpdated, setter=setServiceUpdated:) EDAMTimestamp serviceUpdated;
@property (nonatomic, retain, getter=shareKey, setter=setShareKey:) NSString * shareKey;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, getter=allowPreview, setter=setAllowPreview:) BOOL allowPreview;
#else

- (int64_t) id;
- (void) setId: (int64_t) id;

- (int32_t) userId;
- (void) setUserId: (int32_t) userId;

- (NSString *) notebookGuid;
- (void) setNotebookGuid: (NSString *) notebookGuid;

- (NSString *) email;
- (void) setEmail: (NSString *) email;

- (BOOL) notebookModifiable;
- (void) setNotebookModifiable: (BOOL) notebookModifiable;

- (BOOL) requireLogin;
- (void) setRequireLogin: (BOOL) requireLogin;

- (EDAMTimestamp) serviceCreated;
- (void) setServiceCreated: (EDAMTimestamp) serviceCreated;

- (EDAMTimestamp) serviceUpdated;
- (void) setServiceUpdated: (EDAMTimestamp) serviceUpdated;

- (NSString *) shareKey;
- (void) setShareKey: (NSString *) shareKey;

- (NSString *) username;
- (void) setUsername: (NSString *) username;

- (int) privilege;
- (void) setPrivilege: (int) privilege;

- (BOOL) allowPreview;
- (void) setAllowPreview: (BOOL) allowPreview;

#endif

- (BOOL) idIsSet;
- (BOOL) userIdIsSet;
- (BOOL) notebookGuidIsSet;
- (BOOL) emailIsSet;
- (BOOL) notebookModifiableIsSet;
- (BOOL) requireLoginIsSet;
- (BOOL) serviceCreatedIsSet;
- (BOOL) serviceUpdatedIsSet;
- (BOOL) shareKeyIsSet;
- (BOOL) usernameIsSet;
- (BOOL) privilegeIsSet;
- (BOOL) allowPreviewIsSet;
@end

@interface EDAMNotebookRestrictions : NSObject <NSCoding> {
  BOOL __noReadNotes;
  BOOL __noCreateNotes;
  BOOL __noUpdateNotes;
  BOOL __noExpungeNotes;
  BOOL __noShareNotes;
  BOOL __noEmailNotes;
  BOOL __noSendMessageToRecipients;
  BOOL __noUpdateNotebook;
  BOOL __noExpungeNotebook;
  BOOL __noSetDefaultNotebook;
  BOOL __noSetNotebookStack;
  BOOL __noPublishToPublic;
  BOOL __noPublishToBusinessLibrary;
  BOOL __noCreateTags;
  BOOL __noUpdateTags;
  BOOL __noExpungeTags;
  BOOL __noSetParentTag;
  BOOL __noCreateSharedNotebooks;
  int __updateWhichSharedNotebookRestrictions;
  int __expungeWhichSharedNotebookRestrictions;

  BOOL __noReadNotes_isset;
  BOOL __noCreateNotes_isset;
  BOOL __noUpdateNotes_isset;
  BOOL __noExpungeNotes_isset;
  BOOL __noShareNotes_isset;
  BOOL __noEmailNotes_isset;
  BOOL __noSendMessageToRecipients_isset;
  BOOL __noUpdateNotebook_isset;
  BOOL __noExpungeNotebook_isset;
  BOOL __noSetDefaultNotebook_isset;
  BOOL __noSetNotebookStack_isset;
  BOOL __noPublishToPublic_isset;
  BOOL __noPublishToBusinessLibrary_isset;
  BOOL __noCreateTags_isset;
  BOOL __noUpdateTags_isset;
  BOOL __noExpungeTags_isset;
  BOOL __noSetParentTag_isset;
  BOOL __noCreateSharedNotebooks_isset;
  BOOL __updateWhichSharedNotebookRestrictions_isset;
  BOOL __expungeWhichSharedNotebookRestrictions_isset;
}

- (id) initWithNoReadNotes: (BOOL) noReadNotes noCreateNotes: (BOOL) noCreateNotes noUpdateNotes: (BOOL) noUpdateNotes noExpungeNotes: (BOOL) noExpungeNotes noShareNotes: (BOOL) noShareNotes noEmailNotes: (BOOL) noEmailNotes noSendMessageToRecipients: (BOOL) noSendMessageToRecipients noUpdateNotebook: (BOOL) noUpdateNotebook noExpungeNotebook: (BOOL) noExpungeNotebook noSetDefaultNotebook: (BOOL) noSetDefaultNotebook noSetNotebookStack: (BOOL) noSetNotebookStack noPublishToPublic: (BOOL) noPublishToPublic noPublishToBusinessLibrary: (BOOL) noPublishToBusinessLibrary noCreateTags: (BOOL) noCreateTags noUpdateTags: (BOOL) noUpdateTags noExpungeTags: (BOOL) noExpungeTags noSetParentTag: (BOOL) noSetParentTag noCreateSharedNotebooks: (BOOL) noCreateSharedNotebooks updateWhichSharedNotebookRestrictions: (int) updateWhichSharedNotebookRestrictions expungeWhichSharedNotebookRestrictions: (int) expungeWhichSharedNotebookRestrictions;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=noReadNotes, setter=setNoReadNotes:) BOOL noReadNotes;
@property (nonatomic, getter=noCreateNotes, setter=setNoCreateNotes:) BOOL noCreateNotes;
@property (nonatomic, getter=noUpdateNotes, setter=setNoUpdateNotes:) BOOL noUpdateNotes;
@property (nonatomic, getter=noExpungeNotes, setter=setNoExpungeNotes:) BOOL noExpungeNotes;
@property (nonatomic, getter=noShareNotes, setter=setNoShareNotes:) BOOL noShareNotes;
@property (nonatomic, getter=noEmailNotes, setter=setNoEmailNotes:) BOOL noEmailNotes;
@property (nonatomic, getter=noSendMessageToRecipients, setter=setNoSendMessageToRecipients:) BOOL noSendMessageToRecipients;
@property (nonatomic, getter=noUpdateNotebook, setter=setNoUpdateNotebook:) BOOL noUpdateNotebook;
@property (nonatomic, getter=noExpungeNotebook, setter=setNoExpungeNotebook:) BOOL noExpungeNotebook;
@property (nonatomic, getter=noSetDefaultNotebook, setter=setNoSetDefaultNotebook:) BOOL noSetDefaultNotebook;
@property (nonatomic, getter=noSetNotebookStack, setter=setNoSetNotebookStack:) BOOL noSetNotebookStack;
@property (nonatomic, getter=noPublishToPublic, setter=setNoPublishToPublic:) BOOL noPublishToPublic;
@property (nonatomic, getter=noPublishToBusinessLibrary, setter=setNoPublishToBusinessLibrary:) BOOL noPublishToBusinessLibrary;
@property (nonatomic, getter=noCreateTags, setter=setNoCreateTags:) BOOL noCreateTags;
@property (nonatomic, getter=noUpdateTags, setter=setNoUpdateTags:) BOOL noUpdateTags;
@property (nonatomic, getter=noExpungeTags, setter=setNoExpungeTags:) BOOL noExpungeTags;
@property (nonatomic, getter=noSetParentTag, setter=setNoSetParentTag:) BOOL noSetParentTag;
@property (nonatomic, getter=noCreateSharedNotebooks, setter=setNoCreateSharedNotebooks:) BOOL noCreateSharedNotebooks;
@property (nonatomic, getter=updateWhichSharedNotebookRestrictions, setter=setUpdateWhichSharedNotebookRestrictions:) int updateWhichSharedNotebookRestrictions;
@property (nonatomic, getter=expungeWhichSharedNotebookRestrictions, setter=setExpungeWhichSharedNotebookRestrictions:) int expungeWhichSharedNotebookRestrictions;
#else

- (BOOL) noReadNotes;
- (void) setNoReadNotes: (BOOL) noReadNotes;

- (BOOL) noCreateNotes;
- (void) setNoCreateNotes: (BOOL) noCreateNotes;

- (BOOL) noUpdateNotes;
- (void) setNoUpdateNotes: (BOOL) noUpdateNotes;

- (BOOL) noExpungeNotes;
- (void) setNoExpungeNotes: (BOOL) noExpungeNotes;

- (BOOL) noShareNotes;
- (void) setNoShareNotes: (BOOL) noShareNotes;

- (BOOL) noEmailNotes;
- (void) setNoEmailNotes: (BOOL) noEmailNotes;

- (BOOL) noSendMessageToRecipients;
- (void) setNoSendMessageToRecipients: (BOOL) noSendMessageToRecipients;

- (BOOL) noUpdateNotebook;
- (void) setNoUpdateNotebook: (BOOL) noUpdateNotebook;

- (BOOL) noExpungeNotebook;
- (void) setNoExpungeNotebook: (BOOL) noExpungeNotebook;

- (BOOL) noSetDefaultNotebook;
- (void) setNoSetDefaultNotebook: (BOOL) noSetDefaultNotebook;

- (BOOL) noSetNotebookStack;
- (void) setNoSetNotebookStack: (BOOL) noSetNotebookStack;

- (BOOL) noPublishToPublic;
- (void) setNoPublishToPublic: (BOOL) noPublishToPublic;

- (BOOL) noPublishToBusinessLibrary;
- (void) setNoPublishToBusinessLibrary: (BOOL) noPublishToBusinessLibrary;

- (BOOL) noCreateTags;
- (void) setNoCreateTags: (BOOL) noCreateTags;

- (BOOL) noUpdateTags;
- (void) setNoUpdateTags: (BOOL) noUpdateTags;

- (BOOL) noExpungeTags;
- (void) setNoExpungeTags: (BOOL) noExpungeTags;

- (BOOL) noSetParentTag;
- (void) setNoSetParentTag: (BOOL) noSetParentTag;

- (BOOL) noCreateSharedNotebooks;
- (void) setNoCreateSharedNotebooks: (BOOL) noCreateSharedNotebooks;

- (int) updateWhichSharedNotebookRestrictions;
- (void) setUpdateWhichSharedNotebookRestrictions: (int) updateWhichSharedNotebookRestrictions;

- (int) expungeWhichSharedNotebookRestrictions;
- (void) setExpungeWhichSharedNotebookRestrictions: (int) expungeWhichSharedNotebookRestrictions;

#endif

- (BOOL) noReadNotesIsSet;
- (BOOL) noCreateNotesIsSet;
- (BOOL) noUpdateNotesIsSet;
- (BOOL) noExpungeNotesIsSet;
- (BOOL) noShareNotesIsSet;
- (BOOL) noEmailNotesIsSet;
- (BOOL) noSendMessageToRecipientsIsSet;
- (BOOL) noUpdateNotebookIsSet;
- (BOOL) noExpungeNotebookIsSet;
- (BOOL) noSetDefaultNotebookIsSet;
- (BOOL) noSetNotebookStackIsSet;
- (BOOL) noPublishToPublicIsSet;
- (BOOL) noPublishToBusinessLibraryIsSet;
- (BOOL) noCreateTagsIsSet;
- (BOOL) noUpdateTagsIsSet;
- (BOOL) noExpungeTagsIsSet;
- (BOOL) noSetParentTagIsSet;
- (BOOL) noCreateSharedNotebooksIsSet;
- (BOOL) updateWhichSharedNotebookRestrictionsIsSet;
- (BOOL) expungeWhichSharedNotebookRestrictionsIsSet;
@end

@interface EDAMNotebook : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __name;
  int32_t __updateSequenceNum;
  BOOL __defaultNotebook;
  EDAMTimestamp __serviceCreated;
  EDAMTimestamp __serviceUpdated;
  EDAMPublishing * __publishing;
  BOOL __published;
  NSString * __stack;
  NSArray * __sharedNotebookIds;
  NSArray * __sharedNotebooks;
  EDAMBusinessNotebook * __businessNotebook;
  EDAMUser * __contact;
  EDAMNotebookRestrictions * __restrictions;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __defaultNotebook_isset;
  BOOL __serviceCreated_isset;
  BOOL __serviceUpdated_isset;
  BOOL __publishing_isset;
  BOOL __published_isset;
  BOOL __stack_isset;
  BOOL __sharedNotebookIds_isset;
  BOOL __sharedNotebooks_isset;
  BOOL __businessNotebook_isset;
  BOOL __contact_isset;
  BOOL __restrictions_isset;
}

- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name updateSequenceNum: (int32_t) updateSequenceNum defaultNotebook: (BOOL) defaultNotebook serviceCreated: (EDAMTimestamp) serviceCreated serviceUpdated: (EDAMTimestamp) serviceUpdated publishing: (EDAMPublishing *) publishing published: (BOOL) published stack: (NSString *) stack sharedNotebookIds: (NSArray *) sharedNotebookIds sharedNotebooks: (NSArray *) sharedNotebooks businessNotebook: (EDAMBusinessNotebook *) businessNotebook contact: (EDAMUser *) contact restrictions: (EDAMNotebookRestrictions *) restrictions;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
@property (nonatomic, getter=defaultNotebook, setter=setDefaultNotebook:) BOOL defaultNotebook;
@property (nonatomic, getter=serviceCreated, setter=setServiceCreated:) EDAMTimestamp serviceCreated;
@property (nonatomic, getter=serviceUpdated, setter=setServiceUpdated:) EDAMTimestamp serviceUpdated;
@property (nonatomic, retain, getter=publishing, setter=setPublishing:) EDAMPublishing * publishing;
@property (nonatomic, getter=published, setter=setPublished:) BOOL published;
@property (nonatomic, retain, getter=stack, setter=setStack:) NSString * stack;
@property (nonatomic, retain, getter=sharedNotebookIds, setter=setSharedNotebookIds:) NSArray * sharedNotebookIds;
@property (nonatomic, retain, getter=sharedNotebooks, setter=setSharedNotebooks:) NSArray * sharedNotebooks;
@property (nonatomic, retain, getter=businessNotebook, setter=setBusinessNotebook:) EDAMBusinessNotebook * businessNotebook;
@property (nonatomic, retain, getter=contact, setter=setContact:) EDAMUser * contact;
@property (nonatomic, retain, getter=restrictions, setter=setRestrictions:) EDAMNotebookRestrictions * restrictions;
#else

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;

- (NSString *) name;
- (void) setName: (NSString *) name;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;

- (BOOL) defaultNotebook;
- (void) setDefaultNotebook: (BOOL) defaultNotebook;

- (EDAMTimestamp) serviceCreated;
- (void) setServiceCreated: (EDAMTimestamp) serviceCreated;

- (EDAMTimestamp) serviceUpdated;
- (void) setServiceUpdated: (EDAMTimestamp) serviceUpdated;

- (EDAMPublishing *) publishing;
- (void) setPublishing: (EDAMPublishing *) publishing;

- (BOOL) published;
- (void) setPublished: (BOOL) published;

- (NSString *) stack;
- (void) setStack: (NSString *) stack;

- (NSArray *) sharedNotebookIds;
- (void) setSharedNotebookIds: (NSArray *) sharedNotebookIds;

- (NSArray *) sharedNotebooks;
- (void) setSharedNotebooks: (NSArray *) sharedNotebooks;

- (EDAMBusinessNotebook *) businessNotebook;
- (void) setBusinessNotebook: (EDAMBusinessNotebook *) businessNotebook;

- (EDAMUser *) contact;
- (void) setContact: (EDAMUser *) contact;

- (EDAMNotebookRestrictions *) restrictions;
- (void) setRestrictions: (EDAMNotebookRestrictions *) restrictions;

#endif

- (BOOL) guidIsSet;
- (BOOL) nameIsSet;
- (BOOL) updateSequenceNumIsSet;
- (BOOL) defaultNotebookIsSet;
- (BOOL) serviceCreatedIsSet;
- (BOOL) serviceUpdatedIsSet;
- (BOOL) publishingIsSet;
- (BOOL) publishedIsSet;
- (BOOL) stackIsSet;
- (BOOL) sharedNotebookIdsIsSet;
- (BOOL) sharedNotebooksIsSet;
- (BOOL) businessNotebookIsSet;
- (BOOL) contactIsSet;
- (BOOL) restrictionsIsSet;
@end

@interface EDAMLinkedNotebook : NSObject <NSCoding> {
  NSString * __shareName;
  NSString * __username;
  NSString * __shardId;
  NSString * __shareKey;
  NSString * __uri;
  EDAMGuid __guid;
  int32_t __updateSequenceNum;
  NSString * __noteStoreUrl;
  NSString * __webApiUrlPrefix;
  NSString * __stack;
  int32_t __businessId;

  BOOL __shareName_isset;
  BOOL __username_isset;
  BOOL __shardId_isset;
  BOOL __shareKey_isset;
  BOOL __uri_isset;
  BOOL __guid_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __noteStoreUrl_isset;
  BOOL __webApiUrlPrefix_isset;
  BOOL __stack_isset;
  BOOL __businessId_isset;
}

- (id) initWithShareName: (NSString *) shareName username: (NSString *) username shardId: (NSString *) shardId shareKey: (NSString *) shareKey uri: (NSString *) uri guid: (EDAMGuid) guid updateSequenceNum: (int32_t) updateSequenceNum noteStoreUrl: (NSString *) noteStoreUrl webApiUrlPrefix: (NSString *) webApiUrlPrefix stack: (NSString *) stack businessId: (int32_t) businessId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=shareName, setter=setShareName:) NSString * shareName;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, retain, getter=shardId, setter=setShardId:) NSString * shardId;
@property (nonatomic, retain, getter=shareKey, setter=setShareKey:) NSString * shareKey;
@property (nonatomic, retain, getter=uri, setter=setUri:) NSString * uri;
@property (nonatomic, retain, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
@property (nonatomic, retain, getter=noteStoreUrl, setter=setNoteStoreUrl:) NSString * noteStoreUrl;
@property (nonatomic, retain, getter=webApiUrlPrefix, setter=setWebApiUrlPrefix:) NSString * webApiUrlPrefix;
@property (nonatomic, retain, getter=stack, setter=setStack:) NSString * stack;
@property (nonatomic, getter=businessId, setter=setBusinessId:) int32_t businessId;
#else

- (NSString *) shareName;
- (void) setShareName: (NSString *) shareName;

- (NSString *) username;
- (void) setUsername: (NSString *) username;

- (NSString *) shardId;
- (void) setShardId: (NSString *) shardId;

- (NSString *) shareKey;
- (void) setShareKey: (NSString *) shareKey;

- (NSString *) uri;
- (void) setUri: (NSString *) uri;

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;

- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;

- (NSString *) noteStoreUrl;
- (void) setNoteStoreUrl: (NSString *) noteStoreUrl;

- (NSString *) webApiUrlPrefix;
- (void) setWebApiUrlPrefix: (NSString *) webApiUrlPrefix;

- (NSString *) stack;
- (void) setStack: (NSString *) stack;

- (int32_t) businessId;
- (void) setBusinessId: (int32_t) businessId;

#endif

- (BOOL) shareNameIsSet;
- (BOOL) usernameIsSet;
- (BOOL) shardIdIsSet;
- (BOOL) shareKeyIsSet;
- (BOOL) uriIsSet;
- (BOOL) guidIsSet;
- (BOOL) updateSequenceNumIsSet;
- (BOOL) noteStoreUrlIsSet;
- (BOOL) webApiUrlPrefixIsSet;
- (BOOL) stackIsSet;
- (BOOL) businessIdIsSet;
@end

@interface EDAMNotebookDescriptor : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __notebookDisplayName;
  NSString * __contactName;
  BOOL __hasSharedNotebook;
  int32_t __joinedUserCount;

  BOOL __guid_isset;
  BOOL __notebookDisplayName_isset;
  BOOL __contactName_isset;
  BOOL __hasSharedNotebook_isset;
  BOOL __joinedUserCount_isset;
}

- (id) initWithGuid: (EDAMGuid) guid notebookDisplayName: (NSString *) notebookDisplayName contactName: (NSString *) contactName hasSharedNotebook: (BOOL) hasSharedNotebook joinedUserCount: (int32_t) joinedUserCount;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, retain, getter=notebookDisplayName, setter=setNotebookDisplayName:) NSString * notebookDisplayName;
@property (nonatomic, retain, getter=contactName, setter=setContactName:) NSString * contactName;
@property (nonatomic, getter=hasSharedNotebook, setter=setHasSharedNotebook:) BOOL hasSharedNotebook;
@property (nonatomic, getter=joinedUserCount, setter=setJoinedUserCount:) int32_t joinedUserCount;
#else

- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;

- (NSString *) notebookDisplayName;
- (void) setNotebookDisplayName: (NSString *) notebookDisplayName;

- (NSString *) contactName;
- (void) setContactName: (NSString *) contactName;

- (BOOL) hasSharedNotebook;
- (void) setHasSharedNotebook: (BOOL) hasSharedNotebook;

- (int32_t) joinedUserCount;
- (void) setJoinedUserCount: (int32_t) joinedUserCount;

#endif

- (BOOL) guidIsSet;
- (BOOL) notebookDisplayNameIsSet;
- (BOOL) contactNameIsSet;
- (BOOL) hasSharedNotebookIsSet;
- (BOOL) joinedUserCountIsSet;
@end

@interface EDAMTypesConstants : NSObject {
}
+ (NSString *) CLASSIFICATION_RECIPE_USER_NON_RECIPE;
+ (NSString *) CLASSIFICATION_RECIPE_USER_RECIPE;
+ (NSString *) CLASSIFICATION_RECIPE_SERVICE_RECIPE;
+ (NSString *) EDAM_NOTE_SOURCE_WEB_CLIP;
+ (NSString *) EDAM_NOTE_SOURCE_MAIL_CLIP;
+ (NSString *) EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY;
@end
