/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"

#import "EDAMLimits.h"

enum EDAMPrivilegeLevel {
  PrivilegeLevel_NORMAL = 1,
  PrivilegeLevel_PREMIUM = 3,
  PrivilegeLevel_MANAGER = 7,
  PrivilegeLevel_SUPPORT = 8,
  PrivilegeLevel_ADMIN = 9
};

enum EDAMQueryFormat {
  QueryFormat_USER = 1,
  QueryFormat_SEXP = 2
};

enum EDAMNoteSortOrder {
  NoteSortOrder_CREATED = 1,
  NoteSortOrder_UPDATED = 2,
  NoteSortOrder_RELEVANCE = 3,
  NoteSortOrder_UPDATE_SEQUENCE_NUMBER = 4,
  NoteSortOrder_TITLE = 5
};

enum EDAMPremiumOrderStatus {
  PremiumOrderStatus_NONE = 0,
  PremiumOrderStatus_PENDING = 1,
  PremiumOrderStatus_ACTIVE = 2,
  PremiumOrderStatus_FAILED = 3,
  PremiumOrderStatus_CANCELLATION_PENDING = 4,
  PremiumOrderStatus_CANCELED = 5
};

enum EDAMSharedNotebookPrivilegeLevel {
  SharedNotebookPrivilegeLevel_READ_NOTEBOOK = 0,
  SharedNotebookPrivilegeLevel_MODIFY_NOTEBOOK_PLUS_ACTIVITY = 1,
  SharedNotebookPrivilegeLevel_READ_NOTEBOOK_PLUS_ACTIVITY = 2,
  SharedNotebookPrivilegeLevel_GROUP = 3,
  SharedNotebookPrivilegeLevel_FULL_ACCESS = 4,
  SharedNotebookPrivilegeLevel_BUSINESS_FULL_ACCESS = 5
};

enum EDAMSponsoredGroupRole {
  SponsoredGroupRole_GROUP_MEMBER = 1,
  SponsoredGroupRole_GROUP_ADMIN = 2,
  SponsoredGroupRole_GROUP_OWNER = 3
};

enum EDAMBusinessUserRole {
  BusinessUserRole_ADMIN = 1,
  BusinessUserRole_NORMAL = 2
};

enum EDAMSharedNotebookInstanceRestrictions {
  SharedNotebookInstanceRestrictions_ONLY_JOINED_OR_PREVIEW = 1,
  SharedNotebookInstanceRestrictions_NO_SHARED_NOTEBOOKS = 2
};

typedef int32_t EDAMUserID;

typedef NSString * EDAMGuid;

typedef int64_t EDAMTimestamp;

@interface EDAMData : NSObject <NSCoding> {
  NSData * __bodyHash;
  int32_t __size;
  NSData * __body;

  BOOL __bodyHash_isset;
  BOOL __size_isset;
  BOOL __body_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=bodyHash, setter=setBodyHash:) NSData * bodyHash;
@property (nonatomic, getter=size, setter=setSize:) int32_t size;
@property (nonatomic, strong, getter=body, setter=setBody:) NSData * body;
#endif

- (id) init;
- (id) initWithBodyHash: (NSData *) bodyHash size: (int32_t) size body: (NSData *) body;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSData *) bodyHash;
- (void) setBodyHash: (NSData *) bodyHash;
#endif
- (BOOL) bodyHashIsSet;

#if !__has_feature(objc_arc)
- (int32_t) size;
- (void) setSize: (int32_t) size;
#endif
- (BOOL) sizeIsSet;

#if !__has_feature(objc_arc)
- (NSData *) body;
- (void) setBody: (NSData *) body;
#endif
- (BOOL) bodyIsSet;

@end

@interface EDAMUserAttributes : NSObject <NSCoding> {
  NSString * __defaultLocationName;
  double __defaultLatitude;
  double __defaultLongitude;
  BOOL __preactivation;
  NSMutableArray * __viewedPromotions;
  NSString * __incomingEmailAddress;
  NSMutableArray * __recentMailedAddresses;
  NSString * __comments;
  EDAMTimestamp __dateAgreedToTermsOfService;
  int32_t __maxReferrals;
  int32_t __referralCount;
  NSString * __refererCode;
  EDAMTimestamp __sentEmailDate;
  int32_t __sentEmailCount;
  int32_t __dailyEmailLimit;
  EDAMTimestamp __emailOptOutDate;
  EDAMTimestamp __partnerEmailOptInDate;
  NSString * __preferredLanguage;
  NSString * __preferredCountry;
  BOOL __clipFullPage;
  NSString * __twitterUserName;
  NSString * __twitterId;
  NSString * __groupName;
  NSString * __recognitionLanguage;
  int64_t __customerProfileId;
  NSString * __referralProof;
  BOOL __educationalDiscount;
  NSString * __businessAddress;
  BOOL __hideSponsorBilling;
  BOOL __taxExempt;

  BOOL __defaultLocationName_isset;
  BOOL __defaultLatitude_isset;
  BOOL __defaultLongitude_isset;
  BOOL __preactivation_isset;
  BOOL __viewedPromotions_isset;
  BOOL __incomingEmailAddress_isset;
  BOOL __recentMailedAddresses_isset;
  BOOL __comments_isset;
  BOOL __dateAgreedToTermsOfService_isset;
  BOOL __maxReferrals_isset;
  BOOL __referralCount_isset;
  BOOL __refererCode_isset;
  BOOL __sentEmailDate_isset;
  BOOL __sentEmailCount_isset;
  BOOL __dailyEmailLimit_isset;
  BOOL __emailOptOutDate_isset;
  BOOL __partnerEmailOptInDate_isset;
  BOOL __preferredLanguage_isset;
  BOOL __preferredCountry_isset;
  BOOL __clipFullPage_isset;
  BOOL __twitterUserName_isset;
  BOOL __twitterId_isset;
  BOOL __groupName_isset;
  BOOL __recognitionLanguage_isset;
  BOOL __customerProfileId_isset;
  BOOL __referralProof_isset;
  BOOL __educationalDiscount_isset;
  BOOL __businessAddress_isset;
  BOOL __hideSponsorBilling_isset;
  BOOL __taxExempt_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=defaultLocationName, setter=setDefaultLocationName:) NSString * defaultLocationName;
@property (nonatomic, getter=defaultLatitude, setter=setDefaultLatitude:) double defaultLatitude;
@property (nonatomic, getter=defaultLongitude, setter=setDefaultLongitude:) double defaultLongitude;
@property (nonatomic, getter=preactivation, setter=setPreactivation:) BOOL preactivation;
@property (nonatomic, strong, getter=viewedPromotions, setter=setViewedPromotions:) NSMutableArray * viewedPromotions;
@property (nonatomic, strong, getter=incomingEmailAddress, setter=setIncomingEmailAddress:) NSString * incomingEmailAddress;
@property (nonatomic, strong, getter=recentMailedAddresses, setter=setRecentMailedAddresses:) NSMutableArray * recentMailedAddresses;
@property (nonatomic, strong, getter=comments, setter=setComments:) NSString * comments;
@property (nonatomic, getter=dateAgreedToTermsOfService, setter=setDateAgreedToTermsOfService:) EDAMTimestamp dateAgreedToTermsOfService;
@property (nonatomic, getter=maxReferrals, setter=setMaxReferrals:) int32_t maxReferrals;
@property (nonatomic, getter=referralCount, setter=setReferralCount:) int32_t referralCount;
@property (nonatomic, strong, getter=refererCode, setter=setRefererCode:) NSString * refererCode;
@property (nonatomic, getter=sentEmailDate, setter=setSentEmailDate:) EDAMTimestamp sentEmailDate;
@property (nonatomic, getter=sentEmailCount, setter=setSentEmailCount:) int32_t sentEmailCount;
@property (nonatomic, getter=dailyEmailLimit, setter=setDailyEmailLimit:) int32_t dailyEmailLimit;
@property (nonatomic, getter=emailOptOutDate, setter=setEmailOptOutDate:) EDAMTimestamp emailOptOutDate;
@property (nonatomic, getter=partnerEmailOptInDate, setter=setPartnerEmailOptInDate:) EDAMTimestamp partnerEmailOptInDate;
@property (nonatomic, strong, getter=preferredLanguage, setter=setPreferredLanguage:) NSString * preferredLanguage;
@property (nonatomic, strong, getter=preferredCountry, setter=setPreferredCountry:) NSString * preferredCountry;
@property (nonatomic, getter=clipFullPage, setter=setClipFullPage:) BOOL clipFullPage;
@property (nonatomic, strong, getter=twitterUserName, setter=setTwitterUserName:) NSString * twitterUserName;
@property (nonatomic, strong, getter=twitterId, setter=setTwitterId:) NSString * twitterId;
@property (nonatomic, strong, getter=groupName, setter=setGroupName:) NSString * groupName;
@property (nonatomic, strong, getter=recognitionLanguage, setter=setRecognitionLanguage:) NSString * recognitionLanguage;
@property (nonatomic, getter=customerProfileId, setter=setCustomerProfileId:) int64_t customerProfileId;
@property (nonatomic, strong, getter=referralProof, setter=setReferralProof:) NSString * referralProof;
@property (nonatomic, getter=educationalDiscount, setter=setEducationalDiscount:) BOOL educationalDiscount;
@property (nonatomic, strong, getter=businessAddress, setter=setBusinessAddress:) NSString * businessAddress;
@property (nonatomic, getter=hideSponsorBilling, setter=setHideSponsorBilling:) BOOL hideSponsorBilling;
@property (nonatomic, getter=taxExempt, setter=setTaxExempt:) BOOL taxExempt;
#endif

- (id) init;
- (id) initWithDefaultLocationName: (NSString *) defaultLocationName defaultLatitude: (double) defaultLatitude defaultLongitude: (double) defaultLongitude preactivation: (BOOL) preactivation viewedPromotions: (NSMutableArray *) viewedPromotions incomingEmailAddress: (NSString *) incomingEmailAddress recentMailedAddresses: (NSMutableArray *) recentMailedAddresses comments: (NSString *) comments dateAgreedToTermsOfService: (EDAMTimestamp) dateAgreedToTermsOfService maxReferrals: (int32_t) maxReferrals referralCount: (int32_t) referralCount refererCode: (NSString *) refererCode sentEmailDate: (EDAMTimestamp) sentEmailDate sentEmailCount: (int32_t) sentEmailCount dailyEmailLimit: (int32_t) dailyEmailLimit emailOptOutDate: (EDAMTimestamp) emailOptOutDate partnerEmailOptInDate: (EDAMTimestamp) partnerEmailOptInDate preferredLanguage: (NSString *) preferredLanguage preferredCountry: (NSString *) preferredCountry clipFullPage: (BOOL) clipFullPage twitterUserName: (NSString *) twitterUserName twitterId: (NSString *) twitterId groupName: (NSString *) groupName recognitionLanguage: (NSString *) recognitionLanguage customerProfileId: (int64_t) customerProfileId referralProof: (NSString *) referralProof educationalDiscount: (BOOL) educationalDiscount businessAddress: (NSString *) businessAddress hideSponsorBilling: (BOOL) hideSponsorBilling taxExempt: (BOOL) taxExempt;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) defaultLocationName;
- (void) setDefaultLocationName: (NSString *) defaultLocationName;
#endif
- (BOOL) defaultLocationNameIsSet;

#if !__has_feature(objc_arc)
- (double) defaultLatitude;
- (void) setDefaultLatitude: (double) defaultLatitude;
#endif
- (BOOL) defaultLatitudeIsSet;

#if !__has_feature(objc_arc)
- (double) defaultLongitude;
- (void) setDefaultLongitude: (double) defaultLongitude;
#endif
- (BOOL) defaultLongitudeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) preactivation;
- (void) setPreactivation: (BOOL) preactivation;
#endif
- (BOOL) preactivationIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) viewedPromotions;
- (void) setViewedPromotions: (NSMutableArray *) viewedPromotions;
#endif
- (BOOL) viewedPromotionsIsSet;

#if !__has_feature(objc_arc)
- (NSString *) incomingEmailAddress;
- (void) setIncomingEmailAddress: (NSString *) incomingEmailAddress;
#endif
- (BOOL) incomingEmailAddressIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) recentMailedAddresses;
- (void) setRecentMailedAddresses: (NSMutableArray *) recentMailedAddresses;
#endif
- (BOOL) recentMailedAddressesIsSet;

#if !__has_feature(objc_arc)
- (NSString *) comments;
- (void) setComments: (NSString *) comments;
#endif
- (BOOL) commentsIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) dateAgreedToTermsOfService;
- (void) setDateAgreedToTermsOfService: (EDAMTimestamp) dateAgreedToTermsOfService;
#endif
- (BOOL) dateAgreedToTermsOfServiceIsSet;

#if !__has_feature(objc_arc)
- (int32_t) maxReferrals;
- (void) setMaxReferrals: (int32_t) maxReferrals;
#endif
- (BOOL) maxReferralsIsSet;

#if !__has_feature(objc_arc)
- (int32_t) referralCount;
- (void) setReferralCount: (int32_t) referralCount;
#endif
- (BOOL) referralCountIsSet;

#if !__has_feature(objc_arc)
- (NSString *) refererCode;
- (void) setRefererCode: (NSString *) refererCode;
#endif
- (BOOL) refererCodeIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) sentEmailDate;
- (void) setSentEmailDate: (EDAMTimestamp) sentEmailDate;
#endif
- (BOOL) sentEmailDateIsSet;

#if !__has_feature(objc_arc)
- (int32_t) sentEmailCount;
- (void) setSentEmailCount: (int32_t) sentEmailCount;
#endif
- (BOOL) sentEmailCountIsSet;

#if !__has_feature(objc_arc)
- (int32_t) dailyEmailLimit;
- (void) setDailyEmailLimit: (int32_t) dailyEmailLimit;
#endif
- (BOOL) dailyEmailLimitIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) emailOptOutDate;
- (void) setEmailOptOutDate: (EDAMTimestamp) emailOptOutDate;
#endif
- (BOOL) emailOptOutDateIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) partnerEmailOptInDate;
- (void) setPartnerEmailOptInDate: (EDAMTimestamp) partnerEmailOptInDate;
#endif
- (BOOL) partnerEmailOptInDateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) preferredLanguage;
- (void) setPreferredLanguage: (NSString *) preferredLanguage;
#endif
- (BOOL) preferredLanguageIsSet;

#if !__has_feature(objc_arc)
- (NSString *) preferredCountry;
- (void) setPreferredCountry: (NSString *) preferredCountry;
#endif
- (BOOL) preferredCountryIsSet;

#if !__has_feature(objc_arc)
- (BOOL) clipFullPage;
- (void) setClipFullPage: (BOOL) clipFullPage;
#endif
- (BOOL) clipFullPageIsSet;

#if !__has_feature(objc_arc)
- (NSString *) twitterUserName;
- (void) setTwitterUserName: (NSString *) twitterUserName;
#endif
- (BOOL) twitterUserNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) twitterId;
- (void) setTwitterId: (NSString *) twitterId;
#endif
- (BOOL) twitterIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) groupName;
- (void) setGroupName: (NSString *) groupName;
#endif
- (BOOL) groupNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) recognitionLanguage;
- (void) setRecognitionLanguage: (NSString *) recognitionLanguage;
#endif
- (BOOL) recognitionLanguageIsSet;

#if !__has_feature(objc_arc)
- (int64_t) customerProfileId;
- (void) setCustomerProfileId: (int64_t) customerProfileId;
#endif
- (BOOL) customerProfileIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) referralProof;
- (void) setReferralProof: (NSString *) referralProof;
#endif
- (BOOL) referralProofIsSet;

#if !__has_feature(objc_arc)
- (BOOL) educationalDiscount;
- (void) setEducationalDiscount: (BOOL) educationalDiscount;
#endif
- (BOOL) educationalDiscountIsSet;

#if !__has_feature(objc_arc)
- (NSString *) businessAddress;
- (void) setBusinessAddress: (NSString *) businessAddress;
#endif
- (BOOL) businessAddressIsSet;

#if !__has_feature(objc_arc)
- (BOOL) hideSponsorBilling;
- (void) setHideSponsorBilling: (BOOL) hideSponsorBilling;
#endif
- (BOOL) hideSponsorBillingIsSet;

#if !__has_feature(objc_arc)
- (BOOL) taxExempt;
- (void) setTaxExempt: (BOOL) taxExempt;
#endif
- (BOOL) taxExemptIsSet;

@end

@interface EDAMAccounting : NSObject <NSCoding> {
  int64_t __uploadLimit;
  EDAMTimestamp __uploadLimitEnd;
  int64_t __uploadLimitNextMonth;
  int __premiumServiceStatus;
  NSString * __premiumOrderNumber;
  NSString * __premiumCommerceService;
  EDAMTimestamp __premiumServiceStart;
  NSString * __premiumServiceSKU;
  EDAMTimestamp __lastSuccessfulCharge;
  EDAMTimestamp __lastFailedCharge;
  NSString * __lastFailedChargeReason;
  EDAMTimestamp __nextPaymentDue;
  EDAMTimestamp __premiumLockUntil;
  EDAMTimestamp __updated;
  NSString * __premiumSubscriptionNumber;
  EDAMTimestamp __lastRequestedCharge;
  NSString * __currency;
  int32_t __unitPrice;
  int32_t __businessId;
  NSString * __businessName;
  int __businessRole;

  BOOL __uploadLimit_isset;
  BOOL __uploadLimitEnd_isset;
  BOOL __uploadLimitNextMonth_isset;
  BOOL __premiumServiceStatus_isset;
  BOOL __premiumOrderNumber_isset;
  BOOL __premiumCommerceService_isset;
  BOOL __premiumServiceStart_isset;
  BOOL __premiumServiceSKU_isset;
  BOOL __lastSuccessfulCharge_isset;
  BOOL __lastFailedCharge_isset;
  BOOL __lastFailedChargeReason_isset;
  BOOL __nextPaymentDue_isset;
  BOOL __premiumLockUntil_isset;
  BOOL __updated_isset;
  BOOL __premiumSubscriptionNumber_isset;
  BOOL __lastRequestedCharge_isset;
  BOOL __currency_isset;
  BOOL __unitPrice_isset;
  BOOL __businessId_isset;
  BOOL __businessName_isset;
  BOOL __businessRole_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=uploadLimit, setter=setUploadLimit:) int64_t uploadLimit;
@property (nonatomic, getter=uploadLimitEnd, setter=setUploadLimitEnd:) EDAMTimestamp uploadLimitEnd;
@property (nonatomic, getter=uploadLimitNextMonth, setter=setUploadLimitNextMonth:) int64_t uploadLimitNextMonth;
@property (nonatomic, getter=premiumServiceStatus, setter=setPremiumServiceStatus:) int premiumServiceStatus;
@property (nonatomic, strong, getter=premiumOrderNumber, setter=setPremiumOrderNumber:) NSString * premiumOrderNumber;
@property (nonatomic, strong, getter=premiumCommerceService, setter=setPremiumCommerceService:) NSString * premiumCommerceService;
@property (nonatomic, getter=premiumServiceStart, setter=setPremiumServiceStart:) EDAMTimestamp premiumServiceStart;
@property (nonatomic, strong, getter=premiumServiceSKU, setter=setPremiumServiceSKU:) NSString * premiumServiceSKU;
@property (nonatomic, getter=lastSuccessfulCharge, setter=setLastSuccessfulCharge:) EDAMTimestamp lastSuccessfulCharge;
@property (nonatomic, getter=lastFailedCharge, setter=setLastFailedCharge:) EDAMTimestamp lastFailedCharge;
@property (nonatomic, strong, getter=lastFailedChargeReason, setter=setLastFailedChargeReason:) NSString * lastFailedChargeReason;
@property (nonatomic, getter=nextPaymentDue, setter=setNextPaymentDue:) EDAMTimestamp nextPaymentDue;
@property (nonatomic, getter=premiumLockUntil, setter=setPremiumLockUntil:) EDAMTimestamp premiumLockUntil;
@property (nonatomic, getter=updated, setter=setUpdated:) EDAMTimestamp updated;
@property (nonatomic, strong, getter=premiumSubscriptionNumber, setter=setPremiumSubscriptionNumber:) NSString * premiumSubscriptionNumber;
@property (nonatomic, getter=lastRequestedCharge, setter=setLastRequestedCharge:) EDAMTimestamp lastRequestedCharge;
@property (nonatomic, strong, getter=currency, setter=setCurrency:) NSString * currency;
@property (nonatomic, getter=unitPrice, setter=setUnitPrice:) int32_t unitPrice;
@property (nonatomic, getter=businessId, setter=setBusinessId:) int32_t businessId;
@property (nonatomic, strong, getter=businessName, setter=setBusinessName:) NSString * businessName;
@property (nonatomic, getter=businessRole, setter=setBusinessRole:) int businessRole;
#endif

- (id) init;
- (id) initWithUploadLimit: (int64_t) uploadLimit uploadLimitEnd: (EDAMTimestamp) uploadLimitEnd uploadLimitNextMonth: (int64_t) uploadLimitNextMonth premiumServiceStatus: (int) premiumServiceStatus premiumOrderNumber: (NSString *) premiumOrderNumber premiumCommerceService: (NSString *) premiumCommerceService premiumServiceStart: (EDAMTimestamp) premiumServiceStart premiumServiceSKU: (NSString *) premiumServiceSKU lastSuccessfulCharge: (EDAMTimestamp) lastSuccessfulCharge lastFailedCharge: (EDAMTimestamp) lastFailedCharge lastFailedChargeReason: (NSString *) lastFailedChargeReason nextPaymentDue: (EDAMTimestamp) nextPaymentDue premiumLockUntil: (EDAMTimestamp) premiumLockUntil updated: (EDAMTimestamp) updated premiumSubscriptionNumber: (NSString *) premiumSubscriptionNumber lastRequestedCharge: (EDAMTimestamp) lastRequestedCharge currency: (NSString *) currency unitPrice: (int32_t) unitPrice businessId: (int32_t) businessId businessName: (NSString *) businessName businessRole: (int) businessRole;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) uploadLimit;
- (void) setUploadLimit: (int64_t) uploadLimit;
#endif
- (BOOL) uploadLimitIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) uploadLimitEnd;
- (void) setUploadLimitEnd: (EDAMTimestamp) uploadLimitEnd;
#endif
- (BOOL) uploadLimitEndIsSet;

#if !__has_feature(objc_arc)
- (int64_t) uploadLimitNextMonth;
- (void) setUploadLimitNextMonth: (int64_t) uploadLimitNextMonth;
#endif
- (BOOL) uploadLimitNextMonthIsSet;

#if !__has_feature(objc_arc)
- (int) premiumServiceStatus;
- (void) setPremiumServiceStatus: (int) premiumServiceStatus;
#endif
- (BOOL) premiumServiceStatusIsSet;

#if !__has_feature(objc_arc)
- (NSString *) premiumOrderNumber;
- (void) setPremiumOrderNumber: (NSString *) premiumOrderNumber;
#endif
- (BOOL) premiumOrderNumberIsSet;

#if !__has_feature(objc_arc)
- (NSString *) premiumCommerceService;
- (void) setPremiumCommerceService: (NSString *) premiumCommerceService;
#endif
- (BOOL) premiumCommerceServiceIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) premiumServiceStart;
- (void) setPremiumServiceStart: (EDAMTimestamp) premiumServiceStart;
#endif
- (BOOL) premiumServiceStartIsSet;

#if !__has_feature(objc_arc)
- (NSString *) premiumServiceSKU;
- (void) setPremiumServiceSKU: (NSString *) premiumServiceSKU;
#endif
- (BOOL) premiumServiceSKUIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) lastSuccessfulCharge;
- (void) setLastSuccessfulCharge: (EDAMTimestamp) lastSuccessfulCharge;
#endif
- (BOOL) lastSuccessfulChargeIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) lastFailedCharge;
- (void) setLastFailedCharge: (EDAMTimestamp) lastFailedCharge;
#endif
- (BOOL) lastFailedChargeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) lastFailedChargeReason;
- (void) setLastFailedChargeReason: (NSString *) lastFailedChargeReason;
#endif
- (BOOL) lastFailedChargeReasonIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) nextPaymentDue;
- (void) setNextPaymentDue: (EDAMTimestamp) nextPaymentDue;
#endif
- (BOOL) nextPaymentDueIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) premiumLockUntil;
- (void) setPremiumLockUntil: (EDAMTimestamp) premiumLockUntil;
#endif
- (BOOL) premiumLockUntilIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;
#endif
- (BOOL) updatedIsSet;

#if !__has_feature(objc_arc)
- (NSString *) premiumSubscriptionNumber;
- (void) setPremiumSubscriptionNumber: (NSString *) premiumSubscriptionNumber;
#endif
- (BOOL) premiumSubscriptionNumberIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) lastRequestedCharge;
- (void) setLastRequestedCharge: (EDAMTimestamp) lastRequestedCharge;
#endif
- (BOOL) lastRequestedChargeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) currency;
- (void) setCurrency: (NSString *) currency;
#endif
- (BOOL) currencyIsSet;

#if !__has_feature(objc_arc)
- (int32_t) unitPrice;
- (void) setUnitPrice: (int32_t) unitPrice;
#endif
- (BOOL) unitPriceIsSet;

#if !__has_feature(objc_arc)
- (int32_t) businessId;
- (void) setBusinessId: (int32_t) businessId;
#endif
- (BOOL) businessIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) businessName;
- (void) setBusinessName: (NSString *) businessName;
#endif
- (BOOL) businessNameIsSet;

#if !__has_feature(objc_arc)
- (int) businessRole;
- (void) setBusinessRole: (int) businessRole;
#endif
- (BOOL) businessRoleIsSet;

@end

@interface EDAMPremiumInfo : NSObject <NSCoding> {
  EDAMTimestamp __currentTime;
  BOOL __premium;
  BOOL __premiumRecurring;
  EDAMTimestamp __premiumExpirationDate;
  BOOL __premiumExtendable;
  BOOL __premiumPending;
  BOOL __premiumCancellationPending;
  BOOL __canPurchaseUploadAllowance;
  NSString * __sponsoredGroupName;
  int __sponsoredGroupRole;

  BOOL __currentTime_isset;
  BOOL __premium_isset;
  BOOL __premiumRecurring_isset;
  BOOL __premiumExpirationDate_isset;
  BOOL __premiumExtendable_isset;
  BOOL __premiumPending_isset;
  BOOL __premiumCancellationPending_isset;
  BOOL __canPurchaseUploadAllowance_isset;
  BOOL __sponsoredGroupName_isset;
  BOOL __sponsoredGroupRole_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=currentTime, setter=setCurrentTime:) EDAMTimestamp currentTime;
@property (nonatomic, getter=premium, setter=setPremium:) BOOL premium;
@property (nonatomic, getter=premiumRecurring, setter=setPremiumRecurring:) BOOL premiumRecurring;
@property (nonatomic, getter=premiumExpirationDate, setter=setPremiumExpirationDate:) EDAMTimestamp premiumExpirationDate;
@property (nonatomic, getter=premiumExtendable, setter=setPremiumExtendable:) BOOL premiumExtendable;
@property (nonatomic, getter=premiumPending, setter=setPremiumPending:) BOOL premiumPending;
@property (nonatomic, getter=premiumCancellationPending, setter=setPremiumCancellationPending:) BOOL premiumCancellationPending;
@property (nonatomic, getter=canPurchaseUploadAllowance, setter=setCanPurchaseUploadAllowance:) BOOL canPurchaseUploadAllowance;
@property (nonatomic, strong, getter=sponsoredGroupName, setter=setSponsoredGroupName:) NSString * sponsoredGroupName;
@property (nonatomic, getter=sponsoredGroupRole, setter=setSponsoredGroupRole:) int sponsoredGroupRole;
#endif

- (id) init;
- (id) initWithCurrentTime: (EDAMTimestamp) currentTime premium: (BOOL) premium premiumRecurring: (BOOL) premiumRecurring premiumExpirationDate: (EDAMTimestamp) premiumExpirationDate premiumExtendable: (BOOL) premiumExtendable premiumPending: (BOOL) premiumPending premiumCancellationPending: (BOOL) premiumCancellationPending canPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance sponsoredGroupName: (NSString *) sponsoredGroupName sponsoredGroupRole: (int) sponsoredGroupRole;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) currentTime;
- (void) setCurrentTime: (EDAMTimestamp) currentTime;
#endif
- (BOOL) currentTimeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premium;
- (void) setPremium: (BOOL) premium;
#endif
- (BOOL) premiumIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premiumRecurring;
- (void) setPremiumRecurring: (BOOL) premiumRecurring;
#endif
- (BOOL) premiumRecurringIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) premiumExpirationDate;
- (void) setPremiumExpirationDate: (EDAMTimestamp) premiumExpirationDate;
#endif
- (BOOL) premiumExpirationDateIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premiumExtendable;
- (void) setPremiumExtendable: (BOOL) premiumExtendable;
#endif
- (BOOL) premiumExtendableIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premiumPending;
- (void) setPremiumPending: (BOOL) premiumPending;
#endif
- (BOOL) premiumPendingIsSet;

#if !__has_feature(objc_arc)
- (BOOL) premiumCancellationPending;
- (void) setPremiumCancellationPending: (BOOL) premiumCancellationPending;
#endif
- (BOOL) premiumCancellationPendingIsSet;

#if !__has_feature(objc_arc)
- (BOOL) canPurchaseUploadAllowance;
- (void) setCanPurchaseUploadAllowance: (BOOL) canPurchaseUploadAllowance;
#endif
- (BOOL) canPurchaseUploadAllowanceIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sponsoredGroupName;
- (void) setSponsoredGroupName: (NSString *) sponsoredGroupName;
#endif
- (BOOL) sponsoredGroupNameIsSet;

#if !__has_feature(objc_arc)
- (int) sponsoredGroupRole;
- (void) setSponsoredGroupRole: (int) sponsoredGroupRole;
#endif
- (BOOL) sponsoredGroupRoleIsSet;

@end

@interface EDAMUser : NSObject <NSCoding> {
  EDAMUserID __id;
  NSString * __username;
  NSString * __email;
  NSString * __name;
  NSString * __timezone;
  int __privilege;
  EDAMTimestamp __created;
  EDAMTimestamp __updated;
  EDAMTimestamp __deleted;
  BOOL __active;
  NSString * __shardId;
  EDAMUserAttributes * __attributes;
  EDAMAccounting * __accounting;
  EDAMPremiumInfo * __premiumInfo;

  BOOL __id_isset;
  BOOL __username_isset;
  BOOL __email_isset;
  BOOL __name_isset;
  BOOL __timezone_isset;
  BOOL __privilege_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
  BOOL __deleted_isset;
  BOOL __active_isset;
  BOOL __shardId_isset;
  BOOL __attributes_isset;
  BOOL __accounting_isset;
  BOOL __premiumInfo_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) EDAMUserID id;
@property (nonatomic, strong, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, strong, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, strong, getter=name, setter=setName:) NSString * name;
@property (nonatomic, strong, getter=timezone, setter=setTimezone:) NSString * timezone;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, getter=created, setter=setCreated:) EDAMTimestamp created;
@property (nonatomic, getter=updated, setter=setUpdated:) EDAMTimestamp updated;
@property (nonatomic, getter=deleted, setter=setDeleted:) EDAMTimestamp deleted;
@property (nonatomic, getter=active, setter=setActive:) BOOL active;
@property (nonatomic, strong, getter=shardId, setter=setShardId:) NSString * shardId;
@property (nonatomic, strong, getter=attributes, setter=setAttributes:) EDAMUserAttributes * attributes;
@property (nonatomic, strong, getter=accounting, setter=setAccounting:) EDAMAccounting * accounting;
@property (nonatomic, strong, getter=premiumInfo, setter=setPremiumInfo:) EDAMPremiumInfo * premiumInfo;
#endif

- (id) init;
- (id) initWithId: (EDAMUserID) id username: (NSString *) username email: (NSString *) email name: (NSString *) name timezone: (NSString *) timezone privilege: (int) privilege created: (EDAMTimestamp) created updated: (EDAMTimestamp) updated deleted: (EDAMTimestamp) deleted active: (BOOL) active shardId: (NSString *) shardId attributes: (EDAMUserAttributes *) attributes accounting: (EDAMAccounting *) accounting premiumInfo: (EDAMPremiumInfo *) premiumInfo;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMUserID) id;
- (void) setId: (EDAMUserID) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) timezone;
- (void) setTimezone: (NSString *) timezone;
#endif
- (BOOL) timezoneIsSet;

#if !__has_feature(objc_arc)
- (int) privilege;
- (void) setPrivilege: (int) privilege;
#endif
- (BOOL) privilegeIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) created;
- (void) setCreated: (EDAMTimestamp) created;
#endif
- (BOOL) createdIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;
#endif
- (BOOL) updatedIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) deleted;
- (void) setDeleted: (EDAMTimestamp) deleted;
#endif
- (BOOL) deletedIsSet;

#if !__has_feature(objc_arc)
- (BOOL) active;
- (void) setActive: (BOOL) active;
#endif
- (BOOL) activeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) shardId;
- (void) setShardId: (NSString *) shardId;
#endif
- (BOOL) shardIdIsSet;

#if !__has_feature(objc_arc)
- (EDAMUserAttributes *) attributes;
- (void) setAttributes: (EDAMUserAttributes *) attributes;
#endif
- (BOOL) attributesIsSet;

#if !__has_feature(objc_arc)
- (EDAMAccounting *) accounting;
- (void) setAccounting: (EDAMAccounting *) accounting;
#endif
- (BOOL) accountingIsSet;

#if !__has_feature(objc_arc)
- (EDAMPremiumInfo *) premiumInfo;
- (void) setPremiumInfo: (EDAMPremiumInfo *) premiumInfo;
#endif
- (BOOL) premiumInfoIsSet;

@end

@interface EDAMTag : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __name;
  EDAMGuid __parentGuid;
  int32_t __updateSequenceNum;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __parentGuid_isset;
  BOOL __updateSequenceNum_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, strong, getter=name, setter=setName:) NSString * name;
@property (nonatomic, strong, getter=parentGuid, setter=setParentGuid:) EDAMGuid parentGuid;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
#endif

- (id) init;
- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name parentGuid: (EDAMGuid) parentGuid updateSequenceNum: (int32_t) updateSequenceNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (EDAMGuid) parentGuid;
- (void) setParentGuid: (EDAMGuid) parentGuid;
#endif
- (BOOL) parentGuidIsSet;

#if !__has_feature(objc_arc)
- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
#endif
- (BOOL) updateSequenceNumIsSet;

@end

@interface EDAMLazyMap : NSObject <NSCoding> {
  NSMutableSet * __keysOnly;
  NSMutableDictionary * __fullMap;

  BOOL __keysOnly_isset;
  BOOL __fullMap_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=keysOnly, setter=setKeysOnly:) NSMutableSet * keysOnly;
@property (nonatomic, strong, getter=fullMap, setter=setFullMap:) NSMutableDictionary * fullMap;
#endif

- (id) init;
- (id) initWithKeysOnly: (NSMutableSet *) keysOnly fullMap: (NSMutableDictionary *) fullMap;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSMutableSet *) keysOnly;
- (void) setKeysOnly: (NSMutableSet *) keysOnly;
#endif
- (BOOL) keysOnlyIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) fullMap;
- (void) setFullMap: (NSMutableDictionary *) fullMap;
#endif
- (BOOL) fullMapIsSet;

@end

@interface EDAMResourceAttributes : NSObject <NSCoding> {
  NSString * __sourceURL;
  EDAMTimestamp __timestamp;
  double __latitude;
  double __longitude;
  double __altitude;
  NSString * __cameraMake;
  NSString * __cameraModel;
  BOOL __clientWillIndex;
  NSString * __recoType;
  NSString * __fileName;
  BOOL __attachment;
  EDAMLazyMap * __applicationData;

  BOOL __sourceURL_isset;
  BOOL __timestamp_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
  BOOL __altitude_isset;
  BOOL __cameraMake_isset;
  BOOL __cameraModel_isset;
  BOOL __clientWillIndex_isset;
  BOOL __recoType_isset;
  BOOL __fileName_isset;
  BOOL __attachment_isset;
  BOOL __applicationData_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=sourceURL, setter=setSourceURL:) NSString * sourceURL;
@property (nonatomic, getter=timestamp, setter=setTimestamp:) EDAMTimestamp timestamp;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
@property (nonatomic, getter=altitude, setter=setAltitude:) double altitude;
@property (nonatomic, strong, getter=cameraMake, setter=setCameraMake:) NSString * cameraMake;
@property (nonatomic, strong, getter=cameraModel, setter=setCameraModel:) NSString * cameraModel;
@property (nonatomic, getter=clientWillIndex, setter=setClientWillIndex:) BOOL clientWillIndex;
@property (nonatomic, strong, getter=recoType, setter=setRecoType:) NSString * recoType;
@property (nonatomic, strong, getter=fileName, setter=setFileName:) NSString * fileName;
@property (nonatomic, getter=attachment, setter=setAttachment:) BOOL attachment;
@property (nonatomic, strong, getter=applicationData, setter=setApplicationData:) EDAMLazyMap * applicationData;
#endif

- (id) init;
- (id) initWithSourceURL: (NSString *) sourceURL timestamp: (EDAMTimestamp) timestamp latitude: (double) latitude longitude: (double) longitude altitude: (double) altitude cameraMake: (NSString *) cameraMake cameraModel: (NSString *) cameraModel clientWillIndex: (BOOL) clientWillIndex recoType: (NSString *) recoType fileName: (NSString *) fileName attachment: (BOOL) attachment applicationData: (EDAMLazyMap *) applicationData;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) sourceURL;
- (void) setSourceURL: (NSString *) sourceURL;
#endif
- (BOOL) sourceURLIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) timestamp;
- (void) setTimestamp: (EDAMTimestamp) timestamp;
#endif
- (BOOL) timestampIsSet;

#if !__has_feature(objc_arc)
- (double) latitude;
- (void) setLatitude: (double) latitude;
#endif
- (BOOL) latitudeIsSet;

#if !__has_feature(objc_arc)
- (double) longitude;
- (void) setLongitude: (double) longitude;
#endif
- (BOOL) longitudeIsSet;

#if !__has_feature(objc_arc)
- (double) altitude;
- (void) setAltitude: (double) altitude;
#endif
- (BOOL) altitudeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cameraMake;
- (void) setCameraMake: (NSString *) cameraMake;
#endif
- (BOOL) cameraMakeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cameraModel;
- (void) setCameraModel: (NSString *) cameraModel;
#endif
- (BOOL) cameraModelIsSet;

#if !__has_feature(objc_arc)
- (BOOL) clientWillIndex;
- (void) setClientWillIndex: (BOOL) clientWillIndex;
#endif
- (BOOL) clientWillIndexIsSet;

#if !__has_feature(objc_arc)
- (NSString *) recoType;
- (void) setRecoType: (NSString *) recoType;
#endif
- (BOOL) recoTypeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) fileName;
- (void) setFileName: (NSString *) fileName;
#endif
- (BOOL) fileNameIsSet;

#if !__has_feature(objc_arc)
- (BOOL) attachment;
- (void) setAttachment: (BOOL) attachment;
#endif
- (BOOL) attachmentIsSet;

#if !__has_feature(objc_arc)
- (EDAMLazyMap *) applicationData;
- (void) setApplicationData: (EDAMLazyMap *) applicationData;
#endif
- (BOOL) applicationDataIsSet;

@end

@interface EDAMResource : NSObject <NSCoding> {
  EDAMGuid __guid;
  EDAMGuid __noteGuid;
  EDAMData * __data;
  NSString * __mime;
  int16_t __width;
  int16_t __height;
  int16_t __duration;
  BOOL __active;
  EDAMData * __recognition;
  EDAMResourceAttributes * __attributes;
  int32_t __updateSequenceNum;
  EDAMData * __alternateData;

  BOOL __guid_isset;
  BOOL __noteGuid_isset;
  BOOL __data_isset;
  BOOL __mime_isset;
  BOOL __width_isset;
  BOOL __height_isset;
  BOOL __duration_isset;
  BOOL __active_isset;
  BOOL __recognition_isset;
  BOOL __attributes_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __alternateData_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, strong, getter=noteGuid, setter=setNoteGuid:) EDAMGuid noteGuid;
@property (nonatomic, strong, getter=data, setter=setData:) EDAMData * data;
@property (nonatomic, strong, getter=mime, setter=setMime:) NSString * mime;
@property (nonatomic, getter=width, setter=setWidth:) int16_t width;
@property (nonatomic, getter=height, setter=setHeight:) int16_t height;
@property (nonatomic, getter=duration, setter=setDuration:) int16_t duration;
@property (nonatomic, getter=active, setter=setActive:) BOOL active;
@property (nonatomic, strong, getter=recognition, setter=setRecognition:) EDAMData * recognition;
@property (nonatomic, strong, getter=attributes, setter=setAttributes:) EDAMResourceAttributes * attributes;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
@property (nonatomic, strong, getter=alternateData, setter=setAlternateData:) EDAMData * alternateData;
#endif

- (id) init;
- (id) initWithGuid: (EDAMGuid) guid noteGuid: (EDAMGuid) noteGuid data: (EDAMData *) data mime: (NSString *) mime width: (int16_t) width height: (int16_t) height duration: (int16_t) duration active: (BOOL) active recognition: (EDAMData *) recognition attributes: (EDAMResourceAttributes *) attributes updateSequenceNum: (int32_t) updateSequenceNum alternateData: (EDAMData *) alternateData;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (EDAMGuid) noteGuid;
- (void) setNoteGuid: (EDAMGuid) noteGuid;
#endif
- (BOOL) noteGuidIsSet;

#if !__has_feature(objc_arc)
- (EDAMData *) data;
- (void) setData: (EDAMData *) data;
#endif
- (BOOL) dataIsSet;

#if !__has_feature(objc_arc)
- (NSString *) mime;
- (void) setMime: (NSString *) mime;
#endif
- (BOOL) mimeIsSet;

#if !__has_feature(objc_arc)
- (int16_t) width;
- (void) setWidth: (int16_t) width;
#endif
- (BOOL) widthIsSet;

#if !__has_feature(objc_arc)
- (int16_t) height;
- (void) setHeight: (int16_t) height;
#endif
- (BOOL) heightIsSet;

#if !__has_feature(objc_arc)
- (int16_t) duration;
- (void) setDuration: (int16_t) duration;
#endif
- (BOOL) durationIsSet;

#if !__has_feature(objc_arc)
- (BOOL) active;
- (void) setActive: (BOOL) active;
#endif
- (BOOL) activeIsSet;

#if !__has_feature(objc_arc)
- (EDAMData *) recognition;
- (void) setRecognition: (EDAMData *) recognition;
#endif
- (BOOL) recognitionIsSet;

#if !__has_feature(objc_arc)
- (EDAMResourceAttributes *) attributes;
- (void) setAttributes: (EDAMResourceAttributes *) attributes;
#endif
- (BOOL) attributesIsSet;

#if !__has_feature(objc_arc)
- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
#endif
- (BOOL) updateSequenceNumIsSet;

#if !__has_feature(objc_arc)
- (EDAMData *) alternateData;
- (void) setAlternateData: (EDAMData *) alternateData;
#endif
- (BOOL) alternateDataIsSet;

@end

@interface EDAMNoteAttributes : NSObject <NSCoding> {
  EDAMTimestamp __subjectDate;
  double __latitude;
  double __longitude;
  double __altitude;
  NSString * __author;
  NSString * __source;
  NSString * __sourceURL;
  NSString * __sourceApplication;
  EDAMTimestamp __shareDate;
  NSString * __placeName;
  NSString * __contentClass;
  EDAMLazyMap * __applicationData;
  NSString * __lastEditedBy;
  NSMutableDictionary * __classifications;

  BOOL __subjectDate_isset;
  BOOL __latitude_isset;
  BOOL __longitude_isset;
  BOOL __altitude_isset;
  BOOL __author_isset;
  BOOL __source_isset;
  BOOL __sourceURL_isset;
  BOOL __sourceApplication_isset;
  BOOL __shareDate_isset;
  BOOL __placeName_isset;
  BOOL __contentClass_isset;
  BOOL __applicationData_isset;
  BOOL __lastEditedBy_isset;
  BOOL __classifications_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=subjectDate, setter=setSubjectDate:) EDAMTimestamp subjectDate;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
@property (nonatomic, getter=altitude, setter=setAltitude:) double altitude;
@property (nonatomic, strong, getter=author, setter=setAuthor:) NSString * author;
@property (nonatomic, strong, getter=source, setter=setSource:) NSString * source;
@property (nonatomic, strong, getter=sourceURL, setter=setSourceURL:) NSString * sourceURL;
@property (nonatomic, strong, getter=sourceApplication, setter=setSourceApplication:) NSString * sourceApplication;
@property (nonatomic, getter=shareDate, setter=setShareDate:) EDAMTimestamp shareDate;
@property (nonatomic, strong, getter=placeName, setter=setPlaceName:) NSString * placeName;
@property (nonatomic, strong, getter=contentClass, setter=setContentClass:) NSString * contentClass;
@property (nonatomic, strong, getter=applicationData, setter=setApplicationData:) EDAMLazyMap * applicationData;
@property (nonatomic, strong, getter=lastEditedBy, setter=setLastEditedBy:) NSString * lastEditedBy;
@property (nonatomic, strong, getter=classifications, setter=setClassifications:) NSMutableDictionary * classifications;
#endif

- (id) init;
- (id) initWithSubjectDate: (EDAMTimestamp) subjectDate latitude: (double) latitude longitude: (double) longitude altitude: (double) altitude author: (NSString *) author source: (NSString *) source sourceURL: (NSString *) sourceURL sourceApplication: (NSString *) sourceApplication shareDate: (EDAMTimestamp) shareDate placeName: (NSString *) placeName contentClass: (NSString *) contentClass applicationData: (EDAMLazyMap *) applicationData lastEditedBy: (NSString *) lastEditedBy classifications: (NSMutableDictionary *) classifications;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) subjectDate;
- (void) setSubjectDate: (EDAMTimestamp) subjectDate;
#endif
- (BOOL) subjectDateIsSet;

#if !__has_feature(objc_arc)
- (double) latitude;
- (void) setLatitude: (double) latitude;
#endif
- (BOOL) latitudeIsSet;

#if !__has_feature(objc_arc)
- (double) longitude;
- (void) setLongitude: (double) longitude;
#endif
- (BOOL) longitudeIsSet;

#if !__has_feature(objc_arc)
- (double) altitude;
- (void) setAltitude: (double) altitude;
#endif
- (BOOL) altitudeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) author;
- (void) setAuthor: (NSString *) author;
#endif
- (BOOL) authorIsSet;

#if !__has_feature(objc_arc)
- (NSString *) source;
- (void) setSource: (NSString *) source;
#endif
- (BOOL) sourceIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceURL;
- (void) setSourceURL: (NSString *) sourceURL;
#endif
- (BOOL) sourceURLIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceApplication;
- (void) setSourceApplication: (NSString *) sourceApplication;
#endif
- (BOOL) sourceApplicationIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) shareDate;
- (void) setShareDate: (EDAMTimestamp) shareDate;
#endif
- (BOOL) shareDateIsSet;

#if !__has_feature(objc_arc)
- (NSString *) placeName;
- (void) setPlaceName: (NSString *) placeName;
#endif
- (BOOL) placeNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contentClass;
- (void) setContentClass: (NSString *) contentClass;
#endif
- (BOOL) contentClassIsSet;

#if !__has_feature(objc_arc)
- (EDAMLazyMap *) applicationData;
- (void) setApplicationData: (EDAMLazyMap *) applicationData;
#endif
- (BOOL) applicationDataIsSet;

#if !__has_feature(objc_arc)
- (NSString *) lastEditedBy;
- (void) setLastEditedBy: (NSString *) lastEditedBy;
#endif
- (BOOL) lastEditedByIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) classifications;
- (void) setClassifications: (NSMutableDictionary *) classifications;
#endif
- (BOOL) classificationsIsSet;

@end

@interface EDAMNote : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __title;
  NSString * __content;
  NSData * __contentHash;
  int32_t __contentLength;
  EDAMTimestamp __created;
  EDAMTimestamp __updated;
  EDAMTimestamp __deleted;
  BOOL __active;
  int32_t __updateSequenceNum;
  NSString * __notebookGuid;
  NSMutableArray * __tagGuids;
  NSMutableArray * __resources;
  EDAMNoteAttributes * __attributes;
  NSMutableArray * __tagNames;

  BOOL __guid_isset;
  BOOL __title_isset;
  BOOL __content_isset;
  BOOL __contentHash_isset;
  BOOL __contentLength_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
  BOOL __deleted_isset;
  BOOL __active_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __notebookGuid_isset;
  BOOL __tagGuids_isset;
  BOOL __resources_isset;
  BOOL __attributes_isset;
  BOOL __tagNames_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, strong, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, strong, getter=content, setter=setContent:) NSString * content;
@property (nonatomic, strong, getter=contentHash, setter=setContentHash:) NSData * contentHash;
@property (nonatomic, getter=contentLength, setter=setContentLength:) int32_t contentLength;
@property (nonatomic, getter=created, setter=setCreated:) EDAMTimestamp created;
@property (nonatomic, getter=updated, setter=setUpdated:) EDAMTimestamp updated;
@property (nonatomic, getter=deleted, setter=setDeleted:) EDAMTimestamp deleted;
@property (nonatomic, getter=active, setter=setActive:) BOOL active;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
@property (nonatomic, strong, getter=notebookGuid, setter=setNotebookGuid:) NSString * notebookGuid;
@property (nonatomic, strong, getter=tagGuids, setter=setTagGuids:) NSMutableArray * tagGuids;
@property (nonatomic, strong, getter=resources, setter=setResources:) NSMutableArray * resources;
@property (nonatomic, strong, getter=attributes, setter=setAttributes:) EDAMNoteAttributes * attributes;
@property (nonatomic, strong, getter=tagNames, setter=setTagNames:) NSMutableArray * tagNames;
#endif

- (id) init;
- (id) initWithGuid: (EDAMGuid) guid title: (NSString *) title content: (NSString *) content contentHash: (NSData *) contentHash contentLength: (int32_t) contentLength created: (EDAMTimestamp) created updated: (EDAMTimestamp) updated deleted: (EDAMTimestamp) deleted active: (BOOL) active updateSequenceNum: (int32_t) updateSequenceNum notebookGuid: (NSString *) notebookGuid tagGuids: (NSMutableArray *) tagGuids resources: (NSMutableArray *) resources attributes: (EDAMNoteAttributes *) attributes tagNames: (NSMutableArray *) tagNames;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content;
- (void) setContent: (NSString *) content;
#endif
- (BOOL) contentIsSet;

#if !__has_feature(objc_arc)
- (NSData *) contentHash;
- (void) setContentHash: (NSData *) contentHash;
#endif
- (BOOL) contentHashIsSet;

#if !__has_feature(objc_arc)
- (int32_t) contentLength;
- (void) setContentLength: (int32_t) contentLength;
#endif
- (BOOL) contentLengthIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) created;
- (void) setCreated: (EDAMTimestamp) created;
#endif
- (BOOL) createdIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) updated;
- (void) setUpdated: (EDAMTimestamp) updated;
#endif
- (BOOL) updatedIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) deleted;
- (void) setDeleted: (EDAMTimestamp) deleted;
#endif
- (BOOL) deletedIsSet;

#if !__has_feature(objc_arc)
- (BOOL) active;
- (void) setActive: (BOOL) active;
#endif
- (BOOL) activeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
#endif
- (BOOL) updateSequenceNumIsSet;

#if !__has_feature(objc_arc)
- (NSString *) notebookGuid;
- (void) setNotebookGuid: (NSString *) notebookGuid;
#endif
- (BOOL) notebookGuidIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) tagGuids;
- (void) setTagGuids: (NSMutableArray *) tagGuids;
#endif
- (BOOL) tagGuidsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) resources;
- (void) setResources: (NSMutableArray *) resources;
#endif
- (BOOL) resourcesIsSet;

#if !__has_feature(objc_arc)
- (EDAMNoteAttributes *) attributes;
- (void) setAttributes: (EDAMNoteAttributes *) attributes;
#endif
- (BOOL) attributesIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) tagNames;
- (void) setTagNames: (NSMutableArray *) tagNames;
#endif
- (BOOL) tagNamesIsSet;

@end

@interface EDAMPublishing : NSObject <NSCoding> {
  NSString * __uri;
  int __order;
  BOOL __ascending;
  NSString * __publicDescription;

  BOOL __uri_isset;
  BOOL __order_isset;
  BOOL __ascending_isset;
  BOOL __publicDescription_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=uri, setter=setUri:) NSString * uri;
@property (nonatomic, getter=order, setter=setOrder:) int order;
@property (nonatomic, getter=ascending, setter=setAscending:) BOOL ascending;
@property (nonatomic, strong, getter=publicDescription, setter=setPublicDescription:) NSString * publicDescription;
#endif

- (id) init;
- (id) initWithUri: (NSString *) uri order: (int) order ascending: (BOOL) ascending publicDescription: (NSString *) publicDescription;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) uri;
- (void) setUri: (NSString *) uri;
#endif
- (BOOL) uriIsSet;

#if !__has_feature(objc_arc)
- (int) order;
- (void) setOrder: (int) order;
#endif
- (BOOL) orderIsSet;

#if !__has_feature(objc_arc)
- (BOOL) ascending;
- (void) setAscending: (BOOL) ascending;
#endif
- (BOOL) ascendingIsSet;

#if !__has_feature(objc_arc)
- (NSString *) publicDescription;
- (void) setPublicDescription: (NSString *) publicDescription;
#endif
- (BOOL) publicDescriptionIsSet;

@end

@interface EDAMBusinessNotebook : NSObject <NSCoding> {
  NSString * __notebookDescription;
  int __privilege;
  BOOL __recommended;

  BOOL __notebookDescription_isset;
  BOOL __privilege_isset;
  BOOL __recommended_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=notebookDescription, setter=setNotebookDescription:) NSString * notebookDescription;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, getter=recommended, setter=setRecommended:) BOOL recommended;
#endif

- (id) init;
- (id) initWithNotebookDescription: (NSString *) notebookDescription privilege: (int) privilege recommended: (BOOL) recommended;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) notebookDescription;
- (void) setNotebookDescription: (NSString *) notebookDescription;
#endif
- (BOOL) notebookDescriptionIsSet;

#if !__has_feature(objc_arc)
- (int) privilege;
- (void) setPrivilege: (int) privilege;
#endif
- (BOOL) privilegeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) recommended;
- (void) setRecommended: (BOOL) recommended;
#endif
- (BOOL) recommendedIsSet;

@end

@interface EDAMSavedSearch : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __name;
  NSString * __query;
  int __format;
  int32_t __updateSequenceNum;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __query_isset;
  BOOL __format_isset;
  BOOL __updateSequenceNum_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, strong, getter=name, setter=setName:) NSString * name;
@property (nonatomic, strong, getter=query, setter=setQuery:) NSString * query;
@property (nonatomic, getter=format, setter=setFormat:) int format;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
#endif

- (id) init;
- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name query: (NSString *) query format: (int) format updateSequenceNum: (int32_t) updateSequenceNum;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) query;
- (void) setQuery: (NSString *) query;
#endif
- (BOOL) queryIsSet;

#if !__has_feature(objc_arc)
- (int) format;
- (void) setFormat: (int) format;
#endif
- (BOOL) formatIsSet;

#if !__has_feature(objc_arc)
- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
#endif
- (BOOL) updateSequenceNumIsSet;

@end

@interface EDAMSharedNotebook : NSObject <NSCoding> {
  int64_t __id;
  int32_t __userId;
  NSString * __notebookGuid;
  NSString * __email;
  BOOL __notebookModifiable;
  BOOL __requireLogin;
  EDAMTimestamp __serviceCreated;
  EDAMTimestamp __serviceUpdated;
  NSString * __shareKey;
  NSString * __username;
  int __privilege;
  BOOL __allowPreview;

  BOOL __id_isset;
  BOOL __userId_isset;
  BOOL __notebookGuid_isset;
  BOOL __email_isset;
  BOOL __notebookModifiable_isset;
  BOOL __requireLogin_isset;
  BOOL __serviceCreated_isset;
  BOOL __serviceUpdated_isset;
  BOOL __shareKey_isset;
  BOOL __username_isset;
  BOOL __privilege_isset;
  BOOL __allowPreview_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, getter=userId, setter=setUserId:) int32_t userId;
@property (nonatomic, strong, getter=notebookGuid, setter=setNotebookGuid:) NSString * notebookGuid;
@property (nonatomic, strong, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, getter=notebookModifiable, setter=setNotebookModifiable:) BOOL notebookModifiable;
@property (nonatomic, getter=requireLogin, setter=setRequireLogin:) BOOL requireLogin;
@property (nonatomic, getter=serviceCreated, setter=setServiceCreated:) EDAMTimestamp serviceCreated;
@property (nonatomic, getter=serviceUpdated, setter=setServiceUpdated:) EDAMTimestamp serviceUpdated;
@property (nonatomic, strong, getter=shareKey, setter=setShareKey:) NSString * shareKey;
@property (nonatomic, strong, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, getter=privilege, setter=setPrivilege:) int privilege;
@property (nonatomic, getter=allowPreview, setter=setAllowPreview:) BOOL allowPreview;
#endif

- (id) init;
- (id) initWithId: (int64_t) id userId: (int32_t) userId notebookGuid: (NSString *) notebookGuid email: (NSString *) email notebookModifiable: (BOOL) notebookModifiable requireLogin: (BOOL) requireLogin serviceCreated: (EDAMTimestamp) serviceCreated serviceUpdated: (EDAMTimestamp) serviceUpdated shareKey: (NSString *) shareKey username: (NSString *) username privilege: (int) privilege allowPreview: (BOOL) allowPreview;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) userId;
- (void) setUserId: (int32_t) userId;
#endif
- (BOOL) userIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) notebookGuid;
- (void) setNotebookGuid: (NSString *) notebookGuid;
#endif
- (BOOL) notebookGuidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (BOOL) notebookModifiable;
- (void) setNotebookModifiable: (BOOL) notebookModifiable;
#endif
- (BOOL) notebookModifiableIsSet;

#if !__has_feature(objc_arc)
- (BOOL) requireLogin;
- (void) setRequireLogin: (BOOL) requireLogin;
#endif
- (BOOL) requireLoginIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) serviceCreated;
- (void) setServiceCreated: (EDAMTimestamp) serviceCreated;
#endif
- (BOOL) serviceCreatedIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) serviceUpdated;
- (void) setServiceUpdated: (EDAMTimestamp) serviceUpdated;
#endif
- (BOOL) serviceUpdatedIsSet;

#if !__has_feature(objc_arc)
- (NSString *) shareKey;
- (void) setShareKey: (NSString *) shareKey;
#endif
- (BOOL) shareKeyIsSet;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

#if !__has_feature(objc_arc)
- (int) privilege;
- (void) setPrivilege: (int) privilege;
#endif
- (BOOL) privilegeIsSet;

#if !__has_feature(objc_arc)
- (BOOL) allowPreview;
- (void) setAllowPreview: (BOOL) allowPreview;
#endif
- (BOOL) allowPreviewIsSet;

@end

@interface EDAMNotebookRestrictions : NSObject <NSCoding> {
  BOOL __noReadNotes;
  BOOL __noCreateNotes;
  BOOL __noUpdateNotes;
  BOOL __noExpungeNotes;
  BOOL __noShareNotes;
  BOOL __noEmailNotes;
  BOOL __noSendMessageToRecipients;
  BOOL __noUpdateNotebook;
  BOOL __noExpungeNotebook;
  BOOL __noSetDefaultNotebook;
  BOOL __noSetNotebookStack;
  BOOL __noPublishToPublic;
  BOOL __noPublishToBusinessLibrary;
  BOOL __noCreateTags;
  BOOL __noUpdateTags;
  BOOL __noExpungeTags;
  BOOL __noSetParentTag;
  BOOL __noCreateSharedNotebooks;
  int __updateWhichSharedNotebookRestrictions;
  int __expungeWhichSharedNotebookRestrictions;

  BOOL __noReadNotes_isset;
  BOOL __noCreateNotes_isset;
  BOOL __noUpdateNotes_isset;
  BOOL __noExpungeNotes_isset;
  BOOL __noShareNotes_isset;
  BOOL __noEmailNotes_isset;
  BOOL __noSendMessageToRecipients_isset;
  BOOL __noUpdateNotebook_isset;
  BOOL __noExpungeNotebook_isset;
  BOOL __noSetDefaultNotebook_isset;
  BOOL __noSetNotebookStack_isset;
  BOOL __noPublishToPublic_isset;
  BOOL __noPublishToBusinessLibrary_isset;
  BOOL __noCreateTags_isset;
  BOOL __noUpdateTags_isset;
  BOOL __noExpungeTags_isset;
  BOOL __noSetParentTag_isset;
  BOOL __noCreateSharedNotebooks_isset;
  BOOL __updateWhichSharedNotebookRestrictions_isset;
  BOOL __expungeWhichSharedNotebookRestrictions_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=noReadNotes, setter=setNoReadNotes:) BOOL noReadNotes;
@property (nonatomic, getter=noCreateNotes, setter=setNoCreateNotes:) BOOL noCreateNotes;
@property (nonatomic, getter=noUpdateNotes, setter=setNoUpdateNotes:) BOOL noUpdateNotes;
@property (nonatomic, getter=noExpungeNotes, setter=setNoExpungeNotes:) BOOL noExpungeNotes;
@property (nonatomic, getter=noShareNotes, setter=setNoShareNotes:) BOOL noShareNotes;
@property (nonatomic, getter=noEmailNotes, setter=setNoEmailNotes:) BOOL noEmailNotes;
@property (nonatomic, getter=noSendMessageToRecipients, setter=setNoSendMessageToRecipients:) BOOL noSendMessageToRecipients;
@property (nonatomic, getter=noUpdateNotebook, setter=setNoUpdateNotebook:) BOOL noUpdateNotebook;
@property (nonatomic, getter=noExpungeNotebook, setter=setNoExpungeNotebook:) BOOL noExpungeNotebook;
@property (nonatomic, getter=noSetDefaultNotebook, setter=setNoSetDefaultNotebook:) BOOL noSetDefaultNotebook;
@property (nonatomic, getter=noSetNotebookStack, setter=setNoSetNotebookStack:) BOOL noSetNotebookStack;
@property (nonatomic, getter=noPublishToPublic, setter=setNoPublishToPublic:) BOOL noPublishToPublic;
@property (nonatomic, getter=noPublishToBusinessLibrary, setter=setNoPublishToBusinessLibrary:) BOOL noPublishToBusinessLibrary;
@property (nonatomic, getter=noCreateTags, setter=setNoCreateTags:) BOOL noCreateTags;
@property (nonatomic, getter=noUpdateTags, setter=setNoUpdateTags:) BOOL noUpdateTags;
@property (nonatomic, getter=noExpungeTags, setter=setNoExpungeTags:) BOOL noExpungeTags;
@property (nonatomic, getter=noSetParentTag, setter=setNoSetParentTag:) BOOL noSetParentTag;
@property (nonatomic, getter=noCreateSharedNotebooks, setter=setNoCreateSharedNotebooks:) BOOL noCreateSharedNotebooks;
@property (nonatomic, getter=updateWhichSharedNotebookRestrictions, setter=setUpdateWhichSharedNotebookRestrictions:) int updateWhichSharedNotebookRestrictions;
@property (nonatomic, getter=expungeWhichSharedNotebookRestrictions, setter=setExpungeWhichSharedNotebookRestrictions:) int expungeWhichSharedNotebookRestrictions;
#endif

- (id) init;
- (id) initWithNoReadNotes: (BOOL) noReadNotes noCreateNotes: (BOOL) noCreateNotes noUpdateNotes: (BOOL) noUpdateNotes noExpungeNotes: (BOOL) noExpungeNotes noShareNotes: (BOOL) noShareNotes noEmailNotes: (BOOL) noEmailNotes noSendMessageToRecipients: (BOOL) noSendMessageToRecipients noUpdateNotebook: (BOOL) noUpdateNotebook noExpungeNotebook: (BOOL) noExpungeNotebook noSetDefaultNotebook: (BOOL) noSetDefaultNotebook noSetNotebookStack: (BOOL) noSetNotebookStack noPublishToPublic: (BOOL) noPublishToPublic noPublishToBusinessLibrary: (BOOL) noPublishToBusinessLibrary noCreateTags: (BOOL) noCreateTags noUpdateTags: (BOOL) noUpdateTags noExpungeTags: (BOOL) noExpungeTags noSetParentTag: (BOOL) noSetParentTag noCreateSharedNotebooks: (BOOL) noCreateSharedNotebooks updateWhichSharedNotebookRestrictions: (int) updateWhichSharedNotebookRestrictions expungeWhichSharedNotebookRestrictions: (int) expungeWhichSharedNotebookRestrictions;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (BOOL) noReadNotes;
- (void) setNoReadNotes: (BOOL) noReadNotes;
#endif
- (BOOL) noReadNotesIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noCreateNotes;
- (void) setNoCreateNotes: (BOOL) noCreateNotes;
#endif
- (BOOL) noCreateNotesIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noUpdateNotes;
- (void) setNoUpdateNotes: (BOOL) noUpdateNotes;
#endif
- (BOOL) noUpdateNotesIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noExpungeNotes;
- (void) setNoExpungeNotes: (BOOL) noExpungeNotes;
#endif
- (BOOL) noExpungeNotesIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noShareNotes;
- (void) setNoShareNotes: (BOOL) noShareNotes;
#endif
- (BOOL) noShareNotesIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noEmailNotes;
- (void) setNoEmailNotes: (BOOL) noEmailNotes;
#endif
- (BOOL) noEmailNotesIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noSendMessageToRecipients;
- (void) setNoSendMessageToRecipients: (BOOL) noSendMessageToRecipients;
#endif
- (BOOL) noSendMessageToRecipientsIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noUpdateNotebook;
- (void) setNoUpdateNotebook: (BOOL) noUpdateNotebook;
#endif
- (BOOL) noUpdateNotebookIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noExpungeNotebook;
- (void) setNoExpungeNotebook: (BOOL) noExpungeNotebook;
#endif
- (BOOL) noExpungeNotebookIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noSetDefaultNotebook;
- (void) setNoSetDefaultNotebook: (BOOL) noSetDefaultNotebook;
#endif
- (BOOL) noSetDefaultNotebookIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noSetNotebookStack;
- (void) setNoSetNotebookStack: (BOOL) noSetNotebookStack;
#endif
- (BOOL) noSetNotebookStackIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noPublishToPublic;
- (void) setNoPublishToPublic: (BOOL) noPublishToPublic;
#endif
- (BOOL) noPublishToPublicIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noPublishToBusinessLibrary;
- (void) setNoPublishToBusinessLibrary: (BOOL) noPublishToBusinessLibrary;
#endif
- (BOOL) noPublishToBusinessLibraryIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noCreateTags;
- (void) setNoCreateTags: (BOOL) noCreateTags;
#endif
- (BOOL) noCreateTagsIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noUpdateTags;
- (void) setNoUpdateTags: (BOOL) noUpdateTags;
#endif
- (BOOL) noUpdateTagsIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noExpungeTags;
- (void) setNoExpungeTags: (BOOL) noExpungeTags;
#endif
- (BOOL) noExpungeTagsIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noSetParentTag;
- (void) setNoSetParentTag: (BOOL) noSetParentTag;
#endif
- (BOOL) noSetParentTagIsSet;

#if !__has_feature(objc_arc)
- (BOOL) noCreateSharedNotebooks;
- (void) setNoCreateSharedNotebooks: (BOOL) noCreateSharedNotebooks;
#endif
- (BOOL) noCreateSharedNotebooksIsSet;

#if !__has_feature(objc_arc)
- (int) updateWhichSharedNotebookRestrictions;
- (void) setUpdateWhichSharedNotebookRestrictions: (int) updateWhichSharedNotebookRestrictions;
#endif
- (BOOL) updateWhichSharedNotebookRestrictionsIsSet;

#if !__has_feature(objc_arc)
- (int) expungeWhichSharedNotebookRestrictions;
- (void) setExpungeWhichSharedNotebookRestrictions: (int) expungeWhichSharedNotebookRestrictions;
#endif
- (BOOL) expungeWhichSharedNotebookRestrictionsIsSet;

@end

@interface EDAMNotebook : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __name;
  int32_t __updateSequenceNum;
  BOOL __defaultNotebook;
  EDAMTimestamp __serviceCreated;
  EDAMTimestamp __serviceUpdated;
  EDAMPublishing * __publishing;
  BOOL __published;
  NSString * __stack;
  NSMutableArray * __sharedNotebookIds;
  NSMutableArray * __sharedNotebooks;
  EDAMBusinessNotebook * __businessNotebook;
  EDAMUser * __contact;
  EDAMNotebookRestrictions * __restrictions;

  BOOL __guid_isset;
  BOOL __name_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __defaultNotebook_isset;
  BOOL __serviceCreated_isset;
  BOOL __serviceUpdated_isset;
  BOOL __publishing_isset;
  BOOL __published_isset;
  BOOL __stack_isset;
  BOOL __sharedNotebookIds_isset;
  BOOL __sharedNotebooks_isset;
  BOOL __businessNotebook_isset;
  BOOL __contact_isset;
  BOOL __restrictions_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, strong, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
@property (nonatomic, getter=defaultNotebook, setter=setDefaultNotebook:) BOOL defaultNotebook;
@property (nonatomic, getter=serviceCreated, setter=setServiceCreated:) EDAMTimestamp serviceCreated;
@property (nonatomic, getter=serviceUpdated, setter=setServiceUpdated:) EDAMTimestamp serviceUpdated;
@property (nonatomic, strong, getter=publishing, setter=setPublishing:) EDAMPublishing * publishing;
@property (nonatomic, getter=published, setter=setPublished:) BOOL published;
@property (nonatomic, strong, getter=stack, setter=setStack:) NSString * stack;
@property (nonatomic, strong, getter=sharedNotebookIds, setter=setSharedNotebookIds:) NSMutableArray * sharedNotebookIds;
@property (nonatomic, strong, getter=sharedNotebooks, setter=setSharedNotebooks:) NSMutableArray * sharedNotebooks;
@property (nonatomic, strong, getter=businessNotebook, setter=setBusinessNotebook:) EDAMBusinessNotebook * businessNotebook;
@property (nonatomic, strong, getter=contact, setter=setContact:) EDAMUser * contact;
@property (nonatomic, strong, getter=restrictions, setter=setRestrictions:) EDAMNotebookRestrictions * restrictions;
#endif

- (id) init;
- (id) initWithGuid: (EDAMGuid) guid name: (NSString *) name updateSequenceNum: (int32_t) updateSequenceNum defaultNotebook: (BOOL) defaultNotebook serviceCreated: (EDAMTimestamp) serviceCreated serviceUpdated: (EDAMTimestamp) serviceUpdated publishing: (EDAMPublishing *) publishing published: (BOOL) published stack: (NSString *) stack sharedNotebookIds: (NSMutableArray *) sharedNotebookIds sharedNotebooks: (NSMutableArray *) sharedNotebooks businessNotebook: (EDAMBusinessNotebook *) businessNotebook contact: (EDAMUser *) contact restrictions: (EDAMNotebookRestrictions *) restrictions;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
#endif
- (BOOL) updateSequenceNumIsSet;

#if !__has_feature(objc_arc)
- (BOOL) defaultNotebook;
- (void) setDefaultNotebook: (BOOL) defaultNotebook;
#endif
- (BOOL) defaultNotebookIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) serviceCreated;
- (void) setServiceCreated: (EDAMTimestamp) serviceCreated;
#endif
- (BOOL) serviceCreatedIsSet;

#if !__has_feature(objc_arc)
- (EDAMTimestamp) serviceUpdated;
- (void) setServiceUpdated: (EDAMTimestamp) serviceUpdated;
#endif
- (BOOL) serviceUpdatedIsSet;

#if !__has_feature(objc_arc)
- (EDAMPublishing *) publishing;
- (void) setPublishing: (EDAMPublishing *) publishing;
#endif
- (BOOL) publishingIsSet;

#if !__has_feature(objc_arc)
- (BOOL) published;
- (void) setPublished: (BOOL) published;
#endif
- (BOOL) publishedIsSet;

#if !__has_feature(objc_arc)
- (NSString *) stack;
- (void) setStack: (NSString *) stack;
#endif
- (BOOL) stackIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) sharedNotebookIds;
- (void) setSharedNotebookIds: (NSMutableArray *) sharedNotebookIds;
#endif
- (BOOL) sharedNotebookIdsIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) sharedNotebooks;
- (void) setSharedNotebooks: (NSMutableArray *) sharedNotebooks;
#endif
- (BOOL) sharedNotebooksIsSet;

#if !__has_feature(objc_arc)
- (EDAMBusinessNotebook *) businessNotebook;
- (void) setBusinessNotebook: (EDAMBusinessNotebook *) businessNotebook;
#endif
- (BOOL) businessNotebookIsSet;

#if !__has_feature(objc_arc)
- (EDAMUser *) contact;
- (void) setContact: (EDAMUser *) contact;
#endif
- (BOOL) contactIsSet;

#if !__has_feature(objc_arc)
- (EDAMNotebookRestrictions *) restrictions;
- (void) setRestrictions: (EDAMNotebookRestrictions *) restrictions;
#endif
- (BOOL) restrictionsIsSet;

@end

@interface EDAMLinkedNotebook : NSObject <NSCoding> {
  NSString * __shareName;
  NSString * __username;
  NSString * __shardId;
  NSString * __shareKey;
  NSString * __uri;
  EDAMGuid __guid;
  int32_t __updateSequenceNum;
  NSString * __noteStoreUrl;
  NSString * __webApiUrlPrefix;
  NSString * __stack;
  int32_t __businessId;

  BOOL __shareName_isset;
  BOOL __username_isset;
  BOOL __shardId_isset;
  BOOL __shareKey_isset;
  BOOL __uri_isset;
  BOOL __guid_isset;
  BOOL __updateSequenceNum_isset;
  BOOL __noteStoreUrl_isset;
  BOOL __webApiUrlPrefix_isset;
  BOOL __stack_isset;
  BOOL __businessId_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=shareName, setter=setShareName:) NSString * shareName;
@property (nonatomic, strong, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, strong, getter=shardId, setter=setShardId:) NSString * shardId;
@property (nonatomic, strong, getter=shareKey, setter=setShareKey:) NSString * shareKey;
@property (nonatomic, strong, getter=uri, setter=setUri:) NSString * uri;
@property (nonatomic, strong, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, getter=updateSequenceNum, setter=setUpdateSequenceNum:) int32_t updateSequenceNum;
@property (nonatomic, strong, getter=noteStoreUrl, setter=setNoteStoreUrl:) NSString * noteStoreUrl;
@property (nonatomic, strong, getter=webApiUrlPrefix, setter=setWebApiUrlPrefix:) NSString * webApiUrlPrefix;
@property (nonatomic, strong, getter=stack, setter=setStack:) NSString * stack;
@property (nonatomic, getter=businessId, setter=setBusinessId:) int32_t businessId;
#endif

- (id) init;
- (id) initWithShareName: (NSString *) shareName username: (NSString *) username shardId: (NSString *) shardId shareKey: (NSString *) shareKey uri: (NSString *) uri guid: (EDAMGuid) guid updateSequenceNum: (int32_t) updateSequenceNum noteStoreUrl: (NSString *) noteStoreUrl webApiUrlPrefix: (NSString *) webApiUrlPrefix stack: (NSString *) stack businessId: (int32_t) businessId;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) shareName;
- (void) setShareName: (NSString *) shareName;
#endif
- (BOOL) shareNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) shardId;
- (void) setShardId: (NSString *) shardId;
#endif
- (BOOL) shardIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) shareKey;
- (void) setShareKey: (NSString *) shareKey;
#endif
- (BOOL) shareKeyIsSet;

#if !__has_feature(objc_arc)
- (NSString *) uri;
- (void) setUri: (NSString *) uri;
#endif
- (BOOL) uriIsSet;

#if !__has_feature(objc_arc)
- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (int32_t) updateSequenceNum;
- (void) setUpdateSequenceNum: (int32_t) updateSequenceNum;
#endif
- (BOOL) updateSequenceNumIsSet;

#if !__has_feature(objc_arc)
- (NSString *) noteStoreUrl;
- (void) setNoteStoreUrl: (NSString *) noteStoreUrl;
#endif
- (BOOL) noteStoreUrlIsSet;

#if !__has_feature(objc_arc)
- (NSString *) webApiUrlPrefix;
- (void) setWebApiUrlPrefix: (NSString *) webApiUrlPrefix;
#endif
- (BOOL) webApiUrlPrefixIsSet;

#if !__has_feature(objc_arc)
- (NSString *) stack;
- (void) setStack: (NSString *) stack;
#endif
- (BOOL) stackIsSet;

#if !__has_feature(objc_arc)
- (int32_t) businessId;
- (void) setBusinessId: (int32_t) businessId;
#endif
- (BOOL) businessIdIsSet;

@end

@interface EDAMNotebookDescriptor : NSObject <NSCoding> {
  EDAMGuid __guid;
  NSString * __notebookDisplayName;
  NSString * __contactName;
  BOOL __hasSharedNotebook;
  int32_t __joinedUserCount;

  BOOL __guid_isset;
  BOOL __notebookDisplayName_isset;
  BOOL __contactName_isset;
  BOOL __hasSharedNotebook_isset;
  BOOL __joinedUserCount_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, strong, getter=guid, setter=setGuid:) EDAMGuid guid;
@property (nonatomic, strong, getter=notebookDisplayName, setter=setNotebookDisplayName:) NSString * notebookDisplayName;
@property (nonatomic, strong, getter=contactName, setter=setContactName:) NSString * contactName;
@property (nonatomic, getter=hasSharedNotebook, setter=setHasSharedNotebook:) BOOL hasSharedNotebook;
@property (nonatomic, getter=joinedUserCount, setter=setJoinedUserCount:) int32_t joinedUserCount;
#endif

- (id) init;
- (id) initWithGuid: (EDAMGuid) guid notebookDisplayName: (NSString *) notebookDisplayName contactName: (NSString *) contactName hasSharedNotebook: (BOOL) hasSharedNotebook joinedUserCount: (int32_t) joinedUserCount;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (EDAMGuid) guid;
- (void) setGuid: (EDAMGuid) guid;
#endif
- (BOOL) guidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) notebookDisplayName;
- (void) setNotebookDisplayName: (NSString *) notebookDisplayName;
#endif
- (BOOL) notebookDisplayNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contactName;
- (void) setContactName: (NSString *) contactName;
#endif
- (BOOL) contactNameIsSet;

#if !__has_feature(objc_arc)
- (BOOL) hasSharedNotebook;
- (void) setHasSharedNotebook: (BOOL) hasSharedNotebook;
#endif
- (BOOL) hasSharedNotebookIsSet;

#if !__has_feature(objc_arc)
- (int32_t) joinedUserCount;
- (void) setJoinedUserCount: (int32_t) joinedUserCount;
#endif
- (BOOL) joinedUserCountIsSet;

@end

@interface EDAMTypesConstants : NSObject {
}
+ (NSString *) CLASSIFICATION_RECIPE_USER_NON_RECIPE;
+ (NSString *) CLASSIFICATION_RECIPE_USER_RECIPE;
+ (NSString *) CLASSIFICATION_RECIPE_SERVICE_RECIPE;
+ (NSString *) EDAM_NOTE_SOURCE_WEB_CLIP;
+ (NSString *) EDAM_NOTE_SOURCE_MAIL_CLIP;
+ (NSString *) EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY;
@end
